expanded enumerate
starkware-libs/stwo-cairo pull request #124
Opened 2024-10-15 11:28 UTC by ohad-starkware

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)

2024-10-15 11:28 UTC, ohad-starkware commented
* **#124** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/124?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ohad-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-19 21:41 UTC, andrewmilson requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9FX0I9B4TedGvI_DwJ:-O9FX0I9B4TedGvI_DwK:byt1hcn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L23)):*
> ```XML
>     }
>     res
> }
> ```

In the other repo I think we are using prefix terminology for these kinds of sums. 
Perhaps we should use the same terminology to be consistent?

I think [..] in markdown is a link so might be better to wrap in ``.



_Suggestion:_
```XML
/// Computes exclusive suffix sum.
///
/// # Example
/// 
/// Given `[1, 2, 3, 4]` returns `[9, 7, 4, 0]`.
pub fn exclusive_suffix_sum<const N: usize>(values: [u32; N]) -> [u32; N] {
    let mut res = [0; N];
    for (i, log_range) in values.iter().skip(1).enumerate().rev() {
        res[i] = log_range + res[i + 1];
    }
    res
}
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9FXV6h5kXbHvvzYOeD:-O9FXV6iBSZ5D6Wehiff:brhun0a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L37)):*
> ```XML
>     }
>     res
> }
> ```

Same here?



_Suggestion:_
```XML
/// Computes exclusive prefix sum.
///
/// # Example
///
/// Given `[1, 2, 3, 4]` returns `[0, 1, 3, 6]`.
pub fn exclusive_prefix_sum<const N: usize>(values: [u32; N]) -> [u32; N] {
    let mut res = [0; N];
    for (i, log_range) in values[..N - 1].iter().enumerate() {
        res[i + 1] = log_range + res[i];
    }
    res
}
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9Go3SR8NWcji3_71BS:-O9Go3SR8NWcji3_71BT:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L55)):*
> ```XML
>     res
> }
> fn write_rep(dst: &mut [PackedM31], iv: PackedM31, step: PackedM31, trailing: u32) {
> ```





_Suggestion:_
```XML
}

fn write_rep(dst: &mut [PackedM31], iv: PackedM31, step: PackedM31, trailing: u32) {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9GlkSL7Q2HGfCFFoWu:-O9GlkSM9efhLM5f6uiy:bkwduzc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L72)):*
> ```XML
>             Simd::<u32, N_LANES>::splat(1),
>         )
>     } else {
> ```

Return early



_Suggestion:_
```XML
    if trailing_bits >= LOG_N_LANES {
        return (PackedM31::zero(), PackedM31::one());
    }
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9FhurI2RHTAJQtZ-zL:-O9FhurI2RHTAJQtZ-zM:b-a0pzft) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L88)):*
> ```XML
>         PackedM31::from_simd_unchecked(simd_step)
>     })
> }
> ```

Can we do this without unsafe?



_Code quote:_
```XML
pub fn compute_iv_and_step(bits: u32, trailing_bits: u32) -> (PackedM31, PackedM31) {
    let (simd_iv, simd_step) = if trailing_bits >= LOG_N_LANES {
        (
            Simd::<u32, N_LANES>::splat(0),
            Simd::<u32, N_LANES>::splat(1),
        )
    } else {
        let log_m = LOG_N_LANES - trailing_bits;
        let iv = Simd::<u32, N_LANES>::from_array(
            (0..(1 << log_m))
                .map(|x| vec![x; 1 << (LOG_N_LANES - log_m)])
                .concat()
                .try_into()
                .unwrap(),
        );
        let step = Simd::<u32, N_LANES>::splat(1 << log_m);
        let mask = Simd::<u32, N_LANES>::splat((1 << bits) - 1);
        (iv & mask, step & mask)
    };
    (unsafe { PackedM31::from_simd_unchecked(simd_iv) }, unsafe {
        PackedM31::from_simd_unchecked(simd_step)
    })
}
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiJS6-V3TW06W3128:-O9aiJS6-V3TW06W3129:bjay049) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L48)):*
> ```XML
> /// Given log_reps = 1, bits = 2, trailing = 1, returns:
> /// [0,0,1,1,2,2,3,3,0,0,1,1,2,2,3,3]
> pub fn generate_expanded_enumeration(log_reps: u32, bits: u32, trailing: u32) -> Vec<PackedM31> {
> ```

Where/how is this used?



_Code quote:_
```XML
pub fn generate_expanded_enumeration(log_reps: u32, bits: u32, trailing: u32) -> Vec<PackedM31> {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiYlhDdVzDHYYtF8M:-O9aiYlhDdVzDHYYtF8N:b99yz5z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L105)):*
> ```XML
> }
> 
> pub fn sparse_representation<const N: usize>(trailing_sum: [u32; N], mut dense: u32) -> [M31; N] {
> ```

Same here. Where/how is this used?


<!-- Sent from Reviewable.io -->

2024-10-20 11:43 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9FX0I9B4TedGvI_DwJ:-O9diC67-9HgKr-2eqRw:biwndpt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L23)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

In the other repo I think we are using prefix terminology for these kinds of sums. 
Perhaps we should use the same terminology to be consistent?

I think [..] in markdown is a link so might be better to wrap in ``.
</blockquote></details>

yeah thanks
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9FXV6h5kXbHvvzYOeD:-O9diDCq3XhzHfVOWAxP:b967twy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L37)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Same here?
</blockquote></details>

deleted after refactor
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9Go3SR8NWcji3_71BS:-O9diZCLBlmmuHyPa4bh:bluogne) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L55)):*
> ```XML
>     res
> }
> fn write_rep(dst: &mut [PackedM31], iv: PackedM31, step: PackedM31, trailing: u32) {
> ```

it was on purpose because it is a sub
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9GlkSL7Q2HGfCFFoWu:-O9dizLbCnHYvWOPpyTd:b-j98764) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L72)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Return early
</blockquote></details>

thanks, 
went another route entirly but this is better.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9FhurI2RHTAJQtZ-zL:-O9dj5sS7LOQ53z64SIy:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L88)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Can we do this without unsafe?
</blockquote></details>

same
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiJS6-V3TW06W3128:-O9diIBQ6amuvGAfKkg2:b-oa7n5b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L48)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Where/how is this used?
</blockquote></details>

used to create the cartesian product columns for vectorised rangecheck, probably for bitwise xor operations in the future.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiYlhDdVzDHYYtF8M:-O9dj74HDxd6RVvQmPto:b8iwi9u) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L105)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

Same here. Where/how is this used?
</blockquote></details>

add some docs. wdyt?


<!-- Sent from Reviewable.io -->

2024-10-20 12:22 UTC, shaharsamocha7 requested changes
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiJS6-V3TW06W3128:-O9drEEo76paRx4mW-O7:blxqa5n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L48)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

used to create the cartesian product columns for vectorised rangecheck, probably for bitwise xor operations in the future.
</blockquote></details>

I see that you only use it for tests, can you remove this function?
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiYlhDdVzDHYYtF8M:-O9drfng-InIySOshxTF:b-4afgfa) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L105)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

add some docs. wdyt?
</blockquote></details>

I don't understand the name of this function?
Maybe this logic can be just inlined to `generate_sparse_enumeration`?
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9drL7_6gGCqeNEjKpS:-O9drL7_6gGCqeNEjKpT:b-ccb8ia) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L14)):*
> ```XML
> pub fn simd_by_index(packed_idx: u32) -> Simd<u32, N_LANES> {
>     SIMD_ENUMERATION_IV + Simd::splat(packed_idx) * SIMD_N_LANES
> }
> ```

I think that instead of this logic you can just initial a Simd with (0..15)
and in each for of the loop just add SIMD_N_LANES.

WDYT?



_Code quote:_
```XML
const SIMD_ENUMERATION_IV: Simd<u32, N_LANES> =
    Simd::from_array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);
const SIMD_N_LANES: Simd<u32, N_LANES> = Simd::from_array([N_LANES as u32; N_LANES]);

/// Computes the i'th vector of a [N_LANES]-packed enumeration.
pub fn simd_by_index(packed_idx: u32) -> Simd<u32, N_LANES> {
    SIMD_ENUMERATION_IV + Simd::splat(packed_idx) * SIMD_N_LANES
}
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds-vA3p5qYl97RLam:-O9ds-vA3p5qYl97RLan:b-hvbrl4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L112)):*
> ```XML
>     use super::{exclusive_suffix_sum, generate_sparse_enumeration};
>     use crate::components::utils::{dense_m31_representation, sparse_m31_representation};
>     #[test]
> ```

add new line



_Code quote:_
```XML
    #[test]
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds3Ti-8cRmkajlKk6:-O9ds3Ti-8cRmkajlKk7:bbsxsge) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L157)):*
> ```XML
>         }
>     }
> ```

Consider to just add a test that create the table in a trivial way (nested for loops)
and compare the output to your code.


<!-- Sent from Reviewable.io -->

2024-10-20 13:58 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9Go3SR8NWcji3_71BS:-O9e67lpCayQ_V9ANzFY:b-x0qtmw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aea1021a589a2d331d60326ea69b8fdce5ff7766/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L55)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it was on purpose because it is a sub
</blockquote></details>

nvm, done.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiJS6-V3TW06W3128:-O9eAR4aB9IFdKAgon1d:b7s7190) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L48)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I see that you only use it for tests, can you remove this function?
</blockquote></details>

added a cfg(test) and a todo.
I do need it now before I implement proper add_inputs.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9aiYlhDdVzDHYYtF8M:-O9e4dTM8DgrSrZK8J2-:bv0n9qq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6228f9417efe8a2180c2cbe7681af699d589b703/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L105)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't understand the name of this function?
Maybe this logic can be just inlined to `generate_sparse_enumeration`?
</blockquote></details>

using it in write_interaction_trace next pr, most likely every interaction trace that uses these
currently in blake its non-simd
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9drL7_6gGCqeNEjKpS:-O9e3pba-oDI5x-UkjG8:buemnph) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L14)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that instead of this logic you can just initial a Simd with (0..15)
and in each for of the loop just add SIMD_N_LANES.

WDYT?
</blockquote></details>

I am also using this in interaction trace, it looked ugly there
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 112 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds-vA3p5qYl97RLam:-O9eA2PLAzbJexrWvwVW:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L112)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

add new line
</blockquote></details>

done.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds3Ti-8cRmkajlKk6:-O9eA9JM9XvbjORriws1:bzahg76) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L157)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to just add a test that create the table in a trivial way (nested for loops)
and compare the output to your code.
</blockquote></details>

id rather have less code, and I am using the dense function in a later pr


<!-- Sent from Reviewable.io -->

2024-10-20 14:25 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: all files reviewed (commit messages unreviewed), 11 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds3Ti-8cRmkajlKk6:-O9eIzVD6aMmyNNz4mri:b18xaqf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L157)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

id rather have less code, and I am using the dense function in a later pr
</blockquote></details>

This comment is not about the dense function.
It's about having a simple test to check your code.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9eI6YFCkg-Chev2tCJ:-O9eI6YFCkg-Chev2tCK:b-v12lho) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5f9071a2da59034f26f5a7eec8efd5c515a307c/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L7)):*
> ```XML
> use stwo_prover::core::fields::m31::{M31, MODULUS_BITS};
> 
> const SIMD_ENUMERATION_IV: Simd<u32, N_LANES> =
> ```

According to the function above this should be the "first" enumeration



_Suggestion:_
```XML
SIMD_ENUMERATION_0
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9eHu_bCf73DzzgNze8:-O9eHu_c3bs_-5GxhTmQ:byp1ktf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5f9071a2da59034f26f5a7eec8efd5c515a307c/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L12)):*
> ```XML
> 
> /// Computes the i'th vector of a [N_LANES]-packed enumeration.
> pub fn simd_by_index(packed_idx: u32) -> Simd<u32, N_LANES> {
> ```

Rename



_Suggestion:_
```XML
pub fn packed_enumeration(idx: u32) -> Simd<u32, N_LANES> {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 20 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9eIWTRBK9mU1uPd0Wl:-O9eIWTRBK9mU1uPd0Wm:b-j2zdly) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5f9071a2da59034f26f5a7eec8efd5c515a307c/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L20)):*
> ```XML
>     let mut res = [0; N];
>     for (i, log_range) in values[1..].iter().enumerate().rev() {
>         res[i] = log_range + res[i + 1];
> ```

log_range not related to this function



_Suggestion:_
```XML
    for (i, v) in values[1..].iter().enumerate().rev() {
        res[i] = v + res[i + 1];
```


<!-- Sent from Reviewable.io -->

2024-10-20 16:29 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: all files reviewed (commit messages unreviewed), 10 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds3Ti-8cRmkajlKk6:-O9e_bhXDLcMPb3jPxvE:b1k6uuz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L157)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

This comment is not about the dense function.
It's about having a simple test to check your code.
</blockquote></details>

it gets very close to the old enumeration code, lmk what you think.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9eI6YFCkg-Chev2tCJ:-O9efowA3f-esLJLPws4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5f9071a2da59034f26f5a7eec8efd5c515a307c/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

According to the function above this should be the "first" enumeration
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9eHu_bCf73DzzgNze8:-O9efpqv-Ppeligkg_Oh:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5f9071a2da59034f26f5a7eec8efd5c515a307c/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L12)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-10-21 06:44 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @andrewmilson and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds3Ti-8cRmkajlKk6:-O9hnjzE74YyFOnrg9Mw:bqygnz8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L157)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it gets very close to the old enumeration code, lmk what you think.
</blockquote></details>

I imagined something the following:
let mut expected = vec![vec![], vec![], vec![]]

for i in range 5, for j in range 3, for k in range 3:
 expected[0].push(i)
 expected[1].push(j)
 expected[2].push(k)


<!-- Sent from Reviewable.io -->

2024-10-21 06:58 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 157 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9ds3Ti-8cRmkajlKk6:-O9hr_WO5S4cF-LOS1Qw:b-7rl0jd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/dee370fd3bf86f6fb60d4997b2448006448b35e5/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L157)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I imagined something the following:
let mut expected = vec![vec![], vec![], vec![]]

for i in range 5, for j in range 3, for k in range 3:
 expected[0].push(i)
 expected[1].push(j)
 expected[2].push(k)
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2024-10-21 07:04 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-:-O9ht2i46c-tLoxmaEox:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @andrewmilson)



<!-- Sent from Reviewable.io -->

2024-10-22 02:59 UTC, andrewmilson requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: all files reviewed, 10 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 76 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9hFWKC1DHw_Mhb2vBt:-O9hFWKC1DHw_Mhb2vBu:b-2fzqon) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b6c9903d9373fe71be535296c00de0a7109814a8/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L76)):*
> ```XML
> /// TODO(Ohad): used for testing, remove.
> #[cfg(test)]
> pub fn sparse_m31_representation<const N: usize>(splits: [u32; N], value: u32) -> [M31; N] {
> ```

If it's just for testing I think it should be in the tests module.



_Suggestion:_
```XML
pub fn split_bits<const N: usize>(split_sizes: [u32; N], value: u32) -> [M31; N] {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9m95SBEPlLugg8NNHR:-O9m95SBEPlLugg8NNHS:b3h4owq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3d1d0e5f4458b12b3f0a78e4c483fb45df175712/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L43)):*
> ```XML
> 
> /// Generates the map from 0..2^(split.sum()) to the corresponding sparse representation.
> pub fn generate_sparse_enumeration<const N: usize>(split: [u32; N]) -> [Vec<PackedM31>; N] {
> ```

If all the functions in here are coupled with range checks I think they should be with the code in range_check_vector not utils.



_Code quote:_
```XML
pub fn generate_sparse_enumeration
```
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 92 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9m9IvY9Ha6qrHKjsPV:-O9m9IvY9Ha6qrHKjsPW:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3d1d0e5f4458b12b3f0a78e4c483fb45df175712/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L92)):*
> ```XML
> 
> #[cfg(test)]
> use stwo_prover::core::fields::m31::M31;
> ```




<!-- Sent from Reviewable.io -->

2024-10-22 05:19 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: all files reviewed, 10 unresolved discussions (waiting on @andrewmilson)

___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 76 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9hFWKC1DHw_Mhb2vBt:-O9meTSYCn7AMocqOw_t:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b6c9903d9373fe71be535296c00de0a7109814a8/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L76)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

If it's just for testing I think it should be in the tests module.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 43 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9m95SBEPlLugg8NNHR:-O9meXxW0ZOex9WZ8mZk:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3d1d0e5f4458b12b3f0a78e4c483fb45df175712/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L43)):*
<details><summary><i>Previously, andrewmilson (Andrew Milson) wrote…</i></summary><blockquote>

If all the functions in here are coupled with range checks I think they should be with the code in range_check_vector not utils.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/utils/mod.rs` line 92 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9m9IvY9Ha6qrHKjsPV:-O9meUUb3UPAg4YSeI2A:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/3d1d0e5f4458b12b3f0a78e4c483fb45df175712/stwo_cairo_prover/crates/prover/src/components/utils/mod.rs#L92)):*
> ```XML
> 
> #[cfg(test)]
> use stwo_prover::core::fields::m31::M31;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-23 05:26 UTC, andrewmilson requested changes
I'm not really sure "sparse" is the right term for the functions in this PR. 
When I think of sparse I think of many zeros. 

What do you think of these changes?

change `packed_sparse_representation` to

```
/// Docs...
fn partition_into_bit_segments<const N: usize>(
    mut value: Simd<u32, N_LANES>,
    n_bits_per_segment: [usize; N],
) -> [Simd<u32, N_LANES>; N] {
    n_bits_per_segment.map(|segment_n_bits| {
        let mask = Simd::splat((1 << segment_n_bits) - 1);
        let segment = value & mask;
        value >>= segment_n_bits;
        segment
    });
}
```

Also rename `generate_sparse_enumeration` (generate_partitioned_enumeration?) and move relevant constants inside the function to help readability.

```
/// Docs...
fn generate_partitioned_enumeration() -> .. {
    const PACKED_ENUMERATION: Simd<u32, N_LANES> = Simd::from_array(array::from_fn(|i| i as u32));
    ...
}
```

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-:-O9rbEUa4QYEsznej5NZ:b-n05k2o)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 13 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9rpHZV91GL6nruyjCM:-O9rpHZWCeaXivrbj1qZ:b-qkvhmz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a636f52c5b3ee3f2deb1a83ed3364ab1ab2fafa1/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L13)):*
> ```XML
> pub fn packed_enumeration_at(idx: u32) -> Simd<u32, N_LANES> {
>     SIMD_ENUMERATION_0 + Simd::splat(idx) * SIMD_N_LANES
> }
> ```

Perhaps nit but I don't think this needs to be a seperate function.
IMO too many small functions like this hurts readability.



_Suggestion:_
```XML
/// Computes the i'th vector of a [N_LANES]-packed enumeration.
pub fn packed_enumeration_at(idx: u32) -> Simd<u32, N_LANES> {
    SIMD_ENUMERATION_0 + Simd::splat(idx * N_LANES)
}
```
___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 37 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9rbdim1MnaHXofNhL1:-O9rbdim1MnaHXofNhL2:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a636f52c5b3ee3f2deb1a83ed3364ab1ab2fafa1/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L37)):*
> ```XML
> // Generates masks for each split size.
> // EXAMPLE: [3, 4, 2] -> [0b111000000, 0b000111100, 0b000000011]
> pub fn simd_masks<const N: usize>(split: [u32; N]) -> [Simd<u32, N_LANES>; N] {
> ```





_Suggestion:_
```XML
fn simd_masks<const N: usize>(split: [u32; N]) -> [Simd<u32, N_LANES>; N] {
```


<!-- Sent from Reviewable.io -->

2024-10-27 07:41 UTC, ohad-starkware reviewed
agreed
I did not understand what you meant by 'move relevant constants',
wdyt?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-:-OABuSvvEbYiGkdcoFYr:boejzht)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 37 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-O9rbdim1MnaHXofNhL1:-OABtslu9ag8TLgsb_f9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a636f52c5b3ee3f2deb1a83ed3364ab1ab2fafa1/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L37)):*
> ```XML
> // Generates masks for each split size.
> // EXAMPLE: [3, 4, 2] -> [0b111000000, 0b000111100, 0b000000011]
> pub fn simd_masks<const N: usize>(split: [u32; N]) -> [Simd<u32, N_LANES>; N] {
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-28 03:59 UTC, andrewmilson requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 0 of 3 files reviewed, 12 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-OAGGDpTB8icTlPiTnhP:-OAGGDpTB8icTlPiTnhQ:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45163d1aac88aed72c2eada86cfbe0850fbedac1/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L24)):*
> ```XML
> /// significant bits.
> ///
> /// # Arguments
> ```





_Suggestion:_
```XML
/// Partitions a number into `N` bit segments.
/// 
/// For example ...
///
/// Each segment is returned as a [`M31`] field element.
```


<!-- Sent from Reviewable.io -->

2024-10-28 08:07 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124)* status: 0 of 3 files reviewed, 12 unresolved discussions (waiting on @andrewmilson and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs` line 24 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-OAGGDpTB8icTlPiTnhP:-OAH9V8G3_oxFrLM8QC-:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/45163d1aac88aed72c2eada86cfbe0850fbedac1/stwo_cairo_prover/crates/prover/src/components/range_check_vector/mod.rs#L24)):*
> ```XML
> /// significant bits.
> ///
> /// # Arguments
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-10-29 03:34 UTC, andrewmilson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/124#-:-OALKm2K2UjHqV2OG8WR:bnfp4nl)* status: 0 of 3 files reviewed, 12 unresolved discussions (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-10-29 06:57 UTC, merged