Stav/update opcode component
starkware-libs/stwo-cairo pull request #192
Opened 2024-11-21 14:28 UTC by Stavbe

2024-11-21 14:59 UTC, Stavbe reviewed
1. Added a struct named `Opcodes` that contains all the different opcode component IDs as they appear in `opcodes.json` and are output by the AIR infrastructure ([https://github.com/starkware\-industries/stwo\-air\-infra/pull/351]
2. Delete the InstructionCount struct and use a dictionary instead.
2. Update `push_instr` in `Instruction` to sort the instructions into the relevant components responsible for proving them.
3. Update the existing tests (`test_jmp_abs`, `test_read_from_small_files`, and `test_read_from_large_files`) to verify the new division into components.
4. Added some new tests.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-:-OCEBNM3709ew4cI7iqJ:b-3cvqdr)* status: 0 of 6 files reviewed, 2 unresolved discussions

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEA9a_EUXHoxu0_tgM:-OCEA9a_EUXHoxu0_tgN:b3zpd34) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L154)):*
> ```XML
> 
>     #[ignore]
>     #[test]
> ```

This test passes when it is not ignored.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEASq50Zu521MP9QzC:-OCEASq50Zu521MP9QzD:b3zpd34) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L191)):*
> ```XML
> 
>     #[ignore]
>     #[test]
> ```

This test passes when it is not ignored.


<!-- Sent from Reviewable.io -->

2024-11-21 22:05 UTC, yuvalsw requested changes
Nice!
(note: I didn't review the tests in stwo_cairo_prover/crates/prover/src/lib.rs and the exact logic of dividing to the right components)

> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-:-OCFk6z55rm5D0cAmXA6:b70y0kv)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @ohad-starkware, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEA9a_EUXHoxu0_tgM:-OCFgE_AC3ksrnRAVg6R:b-yliimf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L154)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

This test passes when it is not ignored.
</blockquote></details>

Do you know why it's ignored then? Sounds like the "ignore" can be removed. Same below
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFcZ1A0JsXdH7WIOaw:-OCFcZ1A0JsXdH7WIOax:bauom1t) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L9)):*
> ```XML
> use super::vm_import::TraceEntry;
> 
> /// This struct matches the opcode components list created in `stwo-air-infra`.
> ```

And its purpose is to hold the opcodes used in a Cairo program
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 146 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFdK5L6OX3I0XMKzls:-OCFdK5L6OX3I0XMKzlt:b-ngz47e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L146)):*
> ```XML
>             self.mul_opcode_is_small_f_is_imm_t.len(),
>         );
>         counts.insert("ret_opcode", self.ret_opcode.len());
> ```

suggestion: you should be able to use IndexMap::from([("generic_opcode", self.generic_opcode.len()), ...])



_Code quote:_
```XML
        let mut counts = IndexMap::new();
        counts.insert("generic_opcode", self.generic_opcode.len());
        counts.insert(
            "add_ap_opcode_is_imm_f_op1_base_fp_f",
            self.add_ap_opcode_is_imm_f_op1_base_fp_f.len(),
        );
        counts.insert(
            "add_ap_opcode_is_imm_t_op1_base_fp_f",
            self.add_ap_opcode_is_imm_t_op1_base_fp_f.len(),
        );
        counts.insert(
            "add_ap_opcode_is_imm_f_op1_base_fp_t",
            self.add_ap_opcode_is_imm_f_op1_base_fp_t.len(),
        );
        counts.insert(
            "add_opcode_is_small_t_is_imm_t",
            self.add_opcode_is_small_t_is_imm_t.len(),
        );
        counts.insert(
            "add_opcode_is_small_f_is_imm_f",
            self.add_opcode_is_small_f_is_imm_f.len(),
        );
        counts.insert(
            "add_opcode_is_small_t_is_imm_f",
            self.add_opcode_is_small_t_is_imm_f.len(),
        );
        counts.insert(
            "add_opcode_is_small_f_is_imm_t",
            self.add_opcode_is_small_f_is_imm_t.len(),
        );
        counts.insert(
            "assert_eq_opcode_is_double_deref_f_is_imm_f",
            self.assert_eq_opcode_is_double_deref_f_is_imm_f.len(),
        );
        counts.insert(
            "assert_eq_opcode_is_double_deref_t_is_imm_f",
            self.assert_eq_opcode_is_double_deref_t_is_imm_f.len(),
        );
        counts.insert(
            "assert_eq_opcode_is_double_deref_f_is_imm_t",
            self.assert_eq_opcode_is_double_deref_f_is_imm_t.len(),
        );
        counts.insert(
            "call_opcode_is_rel_f_op1_base_fp_f",
            self.call_opcode_is_rel_f_op1_base_fp_f.len(),
        );
        counts.insert(
            "call_opcode_is_rel_t_op1_base_fp_f",
            self.call_opcode_is_rel_t_op1_base_fp_f.len(),
        );
        counts.insert(
            "call_opcode_is_rel_f_op1_base_fp_t",
            self.call_opcode_is_rel_f_op1_base_fp_t.len(),
        );
        counts.insert(
            "jnz_opcode_is_taken_t_dst_base_fp_t",
            self.jnz_opcode_is_taken_t_dst_base_fp_t.len(),
        );
        counts.insert(
            "jnz_opcode_is_taken_f_dst_base_fp_f",
            self.jnz_opcode_is_taken_f_dst_base_fp_f.len(),
        );
        counts.insert(
            "jnz_opcode_is_taken_t_dst_base_fp_f",
            self.jnz_opcode_is_taken_t_dst_base_fp_f.len(),
        );
        counts.insert(
            "jnz_opcode_is_taken_f_dst_base_fp_t",
            self.jnz_opcode_is_taken_f_dst_base_fp_t.len(),
        );
        counts.insert(
            "jump_opcode_is_rel_t_is_imm_t_is_double_deref_f",
            self.jump_opcode_is_rel_t_is_imm_t_is_double_deref_f.len(),
        );
        counts.insert(
            "jump_opcode_is_rel_t_is_imm_f_is_double_deref_f",
            self.jump_opcode_is_rel_t_is_imm_f_is_double_deref_f.len(),
        );
        counts.insert(
            "jump_opcode_is_rel_f_is_imm_f_is_double_deref_t",
            self.jump_opcode_is_rel_f_is_imm_f_is_double_deref_t.len(),
        );
        counts.insert(
            "jump_opcode_is_rel_f_is_imm_f_is_double_deref_f",
            self.jump_opcode_is_rel_f_is_imm_f_is_double_deref_f.len(),
        );
        counts.insert(
            "mul_opcode_is_small_t_is_imm_t",
            self.mul_opcode_is_small_t_is_imm_t.len(),
        );
        counts.insert(
            "mul_opcode_is_small_t_is_imm_f",
            self.mul_opcode_is_small_t_is_imm_f.len(),
        );
        counts.insert(
            "mul_opcode_is_small_f_is_imm_f",
            self.mul_opcode_is_small_f_is_imm_f.len(),
        );
        counts.insert(
            "mul_opcode_is_small_f_is_imm_t",
            self.mul_opcode_is_small_f_is_imm_t.len(),
        );
        counts.insert("ret_opcode", self.ret_opcode.len());
```
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFe7RgEUbOT5z9Swze:-OCFe7RgEUbOT5z9Swzf:b4tv13a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L162)):*
> ```XML
> 
> #[derive(Debug, Default)]
> pub struct Instructions {
> ```

Should it still be named "Instructions"?
And it should have a doc comment
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFdlmY4hLq-A4NPm-z:-OCFdlmY4hLq-A4NPm0-:b-9a9gr0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L165)):*
> ```XML
>     pub initial_state: CasmState,
>     pub final_state: CasmState,
>     pub components: Opcodes,
> ```

There should be a distinction between opcodes (casm instructions?) and components (there might be 2 components for a single opcode), so this is confusing.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFfTqgCWzgneD08Kro:-OCFfTqgCWzgneD08Krp:b-vkuqsb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L186)):*
> ```XML
> 
>     /// Adds the instruction at the given PC to the component that proves it.
>     fn push_instr(&mut self, mem: &mut MemoryBuilder, state: CasmState) {
> ```

I hope not, as this implementation is much more readable than the previous one, but did you check that this doesn't slow down the adapter too much?
___
*[`stwo_cairo_prover/crates/prover/src/input [...]

2024-11-24 11:09 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 5 of 6 files reviewed, 13 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEA9a_EUXHoxu0_tgM:-OCSpPdLCd6hxkcEmSpW:bxd1fs4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L154)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Do you know why it's ignored then? Sounds like the "ignore" can be removed. Same below
</blockquote></details>

how long does it take
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEASq50Zu521MP9QzC:-OCSr8oY-jRosscgcqF2:b-mjktah) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L191)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

This test passes when it is not ignored.
</blockquote></details>

I don't remember why I did that but if it's quick we should unignore
good point
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFgf_eBUgleqgSvAjT:-OCSpVlI59rRuZ-1wvQh:bn9up7h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L161)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

these and other comments below should be fixed, right?
or if they describe the components, this is clear from the names and can be removed.
</blockquote></details>

This test will be hard to maintain when/if the tested cairo code changes,
can you test on a small program that is strictly dedicated to that test? or find some other way to test it
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSqaGU94nmh9sl8JVr:-OCSqaGU94nmh9sl8JVs:blk40xj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L9)):*
> ```XML
> use super::vm_import::TraceEntry;
> 
> /// This struct matches the opcode components list created in `stwo-air-infra`.
> ```

we shouldn't mention the existence of `stwo-air-infra` in a public repo.
it should match the opcodes in the cairo-air (it doesn't currently)



_Suggestion:_
```XML
Matches the opcodes' air used by 'stwo-cairo-air'.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSr3jtDuSVWX83fIHN:-OCSr3jtDuSVWX83fIHO:bskct99) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L10)):*
> ```XML
> 
> /// This struct matches the opcode components list created in `stwo-air-infra`.
> /// TODO: Ensure it syncs with that list.
> ```

who is this todo for?



_Code quote:_
```XML
TODO: 
```
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSqKbwA018nWEvMGh5:-OCSqKbwA018nWEvMGh6:b-p9vbfl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L43)):*
> ```XML
> 
> impl Opcodes {
>     pub fn counts(&self) -> IndexMap<&str, usize> {
> ```

is it better than dedicated fields?
the benefit  is you can counts._ and the IDE gives suggestions


<!-- Sent from Reviewable.io -->

2024-11-24 14:53 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 2 of 10 files reviewed, 10 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEA9a_EUXHoxu0_tgM:-OCTJENKEOhFfsDAGLUR:bj51gex) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L154)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

how long does it take
</blockquote></details>

Because they use git lfs
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEASq50Zu521MP9QzC:-OCTawN04FgjbumGhmaK:b-x59zrt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L191)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I don't remember why I did that but if it's quick we should unignore
good point
</blockquote></details>

It uses git lfs
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFgf_eBUgleqgSvAjT:-OCT_yki28JMXhvzkDUB:b-nig94s) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L161)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

This test will be hard to maintain when/if the tested cairo code changes,
can you test on a small program that is strictly dedicated to that test? or find some other way to test it
</blockquote></details>

Yuval- The comments are to show that this aligns with the previous component division, as it sums up to the same values. They can be removed before the merge.
Ohad-- I did it in `stwo_cairo_prover/crates/prover/src/lib.rs`, but I felt more confident about it when I saw it working for more complex programs.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFcZ1A0JsXdH7WIOaw:-OCTAvGMEh0e3qLIrInr:btl8eyl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L9)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

And its purpose is to hold the opcodes used in a Cairo program
</blockquote></details>

it's not exactly the opcodes...
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 9 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSqaGU94nmh9sl8JVr:-OCTAud65dXCX0joYKhO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L9)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

we shouldn't mention the existence of `stwo-air-infra` in a public repo.
it should match the opcodes in the cairo-air (it doesn't currently)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSr3jtDuSVWX83fIHN:-OCTAuAG2purQ7tg8UfV:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L10)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

who is this todo for?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSqKbwA018nWEvMGh5:-OCTZr-Y7sUf54VAc8iq:bu10vvv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L43)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

is it better than dedicated fields?
the benefit  is you can counts._ and the IDE gives suggestions
</blockquote></details>

It is a bit wasteful to save two different structs with the same field names that need to stay synchronized with the infra region.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFe7RgEUbOT5z9Swze:-OCTOUCI3a2DloR4PjnX:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L162)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Should it still be named "Instructions"?
And it should have a doc comment
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFdlmY4hLq-A4NPm-z:-OCTEvQ19K1oovTF930p:b-t0xmfu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L165)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There should be a distinction between opcodes (casm instructions?) and components (there might be 2 components for a single opcode), so this is confusing.
</blockquote></details>

How about OpcodeComponents? It's not all the components, only the ones with type=opcode.


<!-- Sent from Reviewable.io -->

2024-11-24 16:16 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFgf_eBUgleqgSvAjT:-OCTxDjk2CdJkE38jgbE:b7vg0tl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L161)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Yuval- The comments are to show that this aligns with the previous component division, as it sums up to the same values. They can be removed before the merge.
Ohad-- I did it in `stwo_cairo_prover/crates/prover/src/lib.rs`, but I felt more confident about it when I saw it working for more complex programs.
</blockquote></details>

yes im just unsetteled about you hard coding a test for large_cairo_input() when it is (/will be) used for other tests and might change


<!-- Sent from Reviewable.io -->

2024-11-24 16:35 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 191 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCEASq50Zu521MP9QzC:-OCTwb_79Dv-4clLQt9Z:b-l4jprq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/372dd1a7eb02af5855dad45f97710b5f2e5108e1/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L191)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

It uses git lfs
</blockquote></details>

right!
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSqKbwA018nWEvMGh5:-OCTwirSETlLoQ0sjAv4:b-c6mjwv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L43)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

It is a bit wasteful to save two different structs with the same field names that need to stay synchronized with the infra region.
</blockquote></details>

you can use macros to reduce that, but I would say that leaving it as plain fields is better than introducing potential panics and typo-induced-bugs
wdyt?
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFdlmY4hLq-A4NPm-z:-OCTvkaXDjm4jzRJdv62:b-p79vw0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L165)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

How about OpcodeComponents? It's not all the components, only the ones with type=opcode.
</blockquote></details>

why would there be 2 components for a single instruction?
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 53 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCU0gLaDQJtZZoANGjw:-OCU0gLaDQJtZZoANGjx:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L53)):*
> ```XML
>     let mut mem_file = std::io::BufReader::new(std::fs::File::open(mem_path)?);
>     let mut mem = MemoryBuilder::from_iter(mem_config, MemEntryIter(&mut mem_file));
>     let state_transition = StateTransition::from_iter(TraceIter(&mut trace_file), &mut mem);
> ```





_Suggestion:_
```XML
state_transitions
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvcB79KeBdFWWNRQs:-OCTvcB79KeBdFWWNRQt:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L164)):*
> ```XML
> /// for proving each transition.
> #[derive(Debug, Default)]
> pub struct StateTransition {
> ```





_Suggestion:_
```XML
StateTransitions
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 187 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvuGEEAsGfe53Kx_f:-OCTvuGEEAsGfe53Kx_g:b-tjagsj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L187)):*
> ```XML
>     }
> 
>     /// Adds the instruction at the given PC to the component that proves it.
> ```

1. this is a sub-routine
2. IMO the code is self documenting, and the doc you added is not 100% accurate.
non-blocking


<!-- Sent from Reviewable.io -->

2024-11-25 06:16 UTC, yuvalsw requested changes
> Reviewed 3 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @ohad-starkware, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFgf_eBUgleqgSvAjT:-OCWxPOh8W9hrvOXmcvo:b81bg3k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L161)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes im just unsetteled about you hard coding a test for large_cairo_input() when it is (/will be) used for other tests and might change
</blockquote></details>

Ah, ok, remove it before merging then
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFdlmY4hLq-A4NPm-z:-OCWvzsT67pMpmqGRaGO:b-spmh7o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L165)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why would there be 2 components for a single instruction?
</blockquote></details>

Not for a single specific instruction, but to a single opcode, depending on the memory (for example, mul of large numbers or small numbers).
Resolved.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvcB79KeBdFWWNRQs:-OCWviL23QWTBpXbR02M:bfxmyy3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L164)):*
> ```XML
> /// for proving each transition.
> #[derive(Debug, Default)]
> pub struct StateTransition {
> ```

why? it's a single transition, isn't it? I think the comment should be fixed to singular rather than this to plural.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 583 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCWwcpJ7YcxAZEKi0sG:-OCWwcpJ7YcxAZEKi0sH:boknk3v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L583)):*
> ```XML
>     }
> 
>     pub fn counts(&self) -> IndexMap<&str, usize> {
> ```

with the new name, this is now confusing. `opcode_components_count`?
Also add doc.


<!-- Sent from Reviewable.io -->

2024-11-25 07:18 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 165 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFdlmY4hLq-A4NPm-z:-OCXA4yx0qoLm2OdYkFI:b-7q8ds9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L165)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Not for a single specific instruction, but to a single opcode, depending on the memory (for example, mul of large numbers or small numbers).
Resolved.
</blockquote></details>

i see
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvcB79KeBdFWWNRQs:-OCXA_byC52ZzN6TX6xF:b-2llt06) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L164)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

why? it's a single transition, isn't it? I think the comment should be fixed to singular rather than this to plural.
</blockquote></details>

Stav's doc is in plural


<!-- Sent from Reviewable.io -->

2024-11-25 15:53 UTC, DavidLevitGurevich requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 2 of 11 files reviewed, 9 unresolved discussions (waiting on @anatgstarkware, @ohad-starkware, @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCZ0HV_647bfJBoIdJc:-OCZ0HV_647bfJBoIdJd:b-dbmjez) (no related file):*
we need to think how to test this, maybe add a todo to make a cairo program that will have count >= 1 for each opcode for which we need to generate a proof or at least test somehow that all constraints pass for it (which should indicate that all chosen components match)


<!-- Sent from Reviewable.io -->

2024-11-26 07:31 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 1 of 13 files reviewed, 4 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 161 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFgf_eBUgleqgSvAjT:-OCbLxlR6KsDV6t0qW0e:bbmiv5y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L161)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Ohad- but it was the same before. I can remove it but than it just an empty test, so what's the point ? i
Yuval- removed
</blockquote></details>

okay then
___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSqKbwA018nWEvMGh5:-OCbLiJbEWrMrK98SBlh:b2nign6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L43)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

So maybe we should not have this function and just do- OpcodeComponents.*name*.len()
</blockquote></details>

yes
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvcB79KeBdFWWNRQs:-OCbLpWK9rbUQKTeyp4C:b-cstnkg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L164)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

I think plural it's more accurate, chnaged to StateTransitions
</blockquote></details>

I agree


<!-- Sent from Reviewable.io -->

2024-11-26 11:51 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @anatgstarkware, @DavidLevitGurevich, @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCSqKbwA018nWEvMGh5:-OCcF3_A885B9CK4vxzj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L43)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 12:04 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCcLJ79C_N850P2mFT-:-OCcLJ79C_N850P2mFT0:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5817db04feacf4e933aedf62ea7b28fbd526f310/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L13)):*
> ```XML
> /// TODO (Stav): Ensure it stays synced with that opcdode AIR's list.
> #[derive(Debug, Default, Clone, Serialize)]
> pub struct OpcodeComponents {
> ```

?



_Suggestion:_
```XML
SortedInstructions
```


<!-- Sent from Reviewable.io -->

2024-11-26 12:07 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 153 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCcMTAZ0ME0if_dMdue:-OCcMTAZ0ME0if_dMduf:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5817db04feacf4e933aedf62ea7b28fbd526f310/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L153)):*
> ```XML
> 
>     // TODO (Stav): Once all the components are in, verify the proof to ensure the division into
>     // components is correct.
> ```





_Suggestion:_
```XML
    // TODO (Stav): Once all the components are in, verify the proof to ensure the sort was correct.
```


<!-- Sent from Reviewable.io -->

2024-11-26 12:08 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 105 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCcMhGPEoNuPmWXj5xF:-OCcMhGPEoNuPmWXj5xG:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5817db04feacf4e933aedf62ea7b28fbd526f310/stwo_cairo_prover/crates/vm_runner/src/main.rs#L105)):*
> ```XML
>         args.output_path,
>         serde_json::to_string(&execution_resources)?,
>     )?;
> ```





_Suggestion:_
```XML
    let execution_resources = &cairo_input.state_transitions.opcode_components;
    std::fs::write(
        args.output_path,
        serde_json::to_string(execution_resources)?,
    )?;
```


<!-- Sent from Reviewable.io -->

2024-11-26 12:10 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 13 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCcNFIzE63T0hdFG4-J:-OCcNFIzE63T0hdFG4-K:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5817db04feacf4e933aedf62ea7b28fbd526f310/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L13)):*
> ```XML
> /// TODO (Stav): Ensure it stays synced with that opcdode AIR's list.
> #[derive(Debug, Default, Clone, Serialize)]
> pub struct OpcodeComponents {
> ```

?



_Suggestion:_
```XML
ExecutionResources 
```


<!-- Sent from Reviewable.io -->

2024-11-26 15:58 UTC, ohad-starkware requested changes
> Reviewed 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 298 at r9](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCd5TOm--MqkjXUs8o_:-OCd5TOm--MqkjXUs8oa:b-5kb41w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bd43a7e2a4806df6bc3cfcc6cbf7962ec79da979/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L298)):*
> ```XML
>             }
> 
>             // jnz
> ```

same below



_Suggestion:_
```XML
jnz.
```


<!-- Sent from Reviewable.io -->

2024-11-27 08:13 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @anatgstarkware, @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 298 at r9](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCd5TOm--MqkjXUs8o_:-OCgfeb7EwB7r_dgJ8p3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bd43a7e2a4806df6bc3cfcc6cbf7962ec79da979/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L298)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

same below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-27 08:41 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 0 of 13 files reviewed, 2 unresolved discussions (waiting on @anatgstarkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 369 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCgm1uN7E7zzyaR_755:-OCgm1uN7E7zzyaR_756:b-2bp8x8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4252a215a173056ed413f8c796398ef593eab8d1/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L369)):*
> ```XML
>             } => {
>                 if op1_imm {
>                     // [ap/fp + offset0] = imm
> ```

and to every doc here



_Suggestion:_
```XML
[ap/fp + offset0] = imm.
```


<!-- Sent from Reviewable.io -->

2024-11-27 17:21 UTC, yuvalsw requested changes
> Reviewed 1 of 9 files at r5, 3 of 10 files at r6, 2 of 7 files at r7, 3 of 6 files at r8, 2 of 3 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @anatgstarkware, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/instructions.rs` line 186 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCFfTqgCWzgneD08Kro:-OCiYWLgEZTN7anpVz8t:b-nfo04j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fdc4e1e8ac17085694114f9e1cad0edc2d9d46cf/stwo_cairo_prover/crates/prover/src/input/instructions.rs#L186)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

I did
</blockquote></details>

Thanks. For posterity, noting here that the increase was, at most, negligible, so we are good.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvcB79KeBdFWWNRQs:-OCiXfx81PfXk5bMxwdA:bccdho6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L164)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I agree
</blockquote></details>

Unless I miss something, this struct represents a single transition of state. The plural name is confusing.
The doc better be singular too IMO
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 14 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiWqsm5qEmroRFoTBI:-OCiWqsn-spIiOvTLFJS:b-jooge6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/plain.rs#L14)):*
> ```XML
> use super::{CairoInput, SegmentAddrs};
> 
> pub fn input_from_plain_casm(
> ```

Please doc `generic_only` and when/why it should be used.
(and maybe the function if already here :) )
___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCic_nl3XDmnrEhJtiI:-OCic_nl3XDmnrEhJtiJ:b-1m734b) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L67)):*
> ```XML
>         import_from_vm_output(args.pub_json.as_path(), args.priv_json.as_path())?;
> 
>     let instruction_counts = &vm_output.state_transitions.vm_state_by_opcode;
> ```

I am not sure we want the whole trace in the log. Counts were somewhat concise and gave some info.
If you still want to have the whole trace and not the counts, the var should be renamed (and the log text).
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 12 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiX7QM9mzCvwo3qSaW:-OCiX7QM9mzCvwo3qSaX:b4fad8w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L12)):*
> ```XML
> /// and should match the opcode's air used by `stwo-cairo-air`.
> /// TODO (Stav): Ensure it stays synced with that opcdode AIR's list.
> #[derive(Debug, Default, Clone, Serialize)]
> ```

Serialize but not Deserialize on purpose?



_Code quote:_
```XML
 Serialize
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 13 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiXKhL7ni-jXgsDvAh:-OCiXKhL7ni-jXgsDvAi:brw0gkb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L13)):*
> ```XML
> /// TODO (Stav): Ensure it stays synced with that opcdode AIR's list.
> #[derive(Debug, Default, Clone, Serialize)]
> pub struct VmStateByOpcode {
> ```

VmState or CasmState?
It holds `CasmState`s



_Code quote:_
```XML
 VmStateByOpcode {
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 53 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiXycv-wFNOkwBPpeR:-OCiXycv-wFNOkwBPpeS:bsihyyy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L53)):*
> ```XML
> }
> 
> /// Holds the state transitions of a Cairo program, sorted according to the components responsible
> ```

"split" is more accurate.



_Suggestion:_
```XML
ogram, split accordin
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 59 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYJWzDGVi0FRJycYa:-OCiYJWzDGVi0FRJycYb:b-e9ep2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L59)):*
> ```XML
>     pub initial_state: CasmState,
>     pub final_state: CasmState,
>     pub vm_state_by_opcode: VmStateByOpcode,
> ```

Sorry for nitpicking, but this, OTOH should be plural. Otherwise it may be read like there is a single vm state belonging/matching any opcode.



_Suggestion:_
```XML
    pub vm_states_by_opcode: VmStatesByOpcode,
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 66 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYyjX6cZvel6ToVW3:-OCiYyjY80lmIweP9sZu:b-6d25h5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L66)):*
> ```XML
>         iter: impl Iterator<Item = TraceEntry>,
>         mem: &mut MemoryBuilder,
>         dev_mode: bool,
> ```

please doc
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 82 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCibA070RE209QVxnff:-OCibA070RE209QVxnfg:b-7cvvs) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L82)):*
> ```XML
>                 break;
>             };
>             res.final_state = (*next).into();
> ```

not super significant, but probably a little faster to avoid the `into` for each opcode. Just keep the current element as last_entry or something, and then after the loop do the .into() only on it.



_Code quote:_
```XML
res.final_state = (*next).into();
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 89 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYjtF16-dDmoiMkTY:-OCiYjtF16-dDmoiMkTZ:b-turaz2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L89)):*
> ```XML
> 
>     // Pushes the state transition at pc into the appropriate opcode component.
>     // TODO(Ohad): remove dev_mode after adding the rest of the instructions.
> ```

triple slash for items docs



_Suggestion:_
```XML
    /// Pushes the state transition at pc into the appropriate opcode component.
    /// TODO(Ohad): remove dev_mode after adding the rest of the instructions.
```
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 101 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCicGhn9xIWK0AHid-W:-OCicGho6300o26EyJ24:bll36gu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/vm_runner/src/main.rs#L101)):*
> ```XML
>     let cairo_input = adapt_vm_output_to_stwo(cairo_runner);
> 
>     let execution_resources = &cairo_input.state_transitions.vm_state_by_opcode;
> ```

We only want the counts as execution resources - why did you  [...]

2024-11-28 07:31 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @anatgstarkware, @shaharsamocha7, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 66 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYyjX6cZvel6ToVW3:-OClcyWN70PlUug3OYQ8:b-4azs75) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

please doc
</blockquote></details>

these changes are already merged
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 82 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCibA070RE209QVxnff:-OCledNh8YpBT7IO2IOf:b-5h08cl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L82)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

not super significant, but probably a little faster to avoid the `into` for each opcode. Just keep the current element as last_entry or something, and then after the loop do the .into() only on it.
</blockquote></details>

same here 
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 89 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYjtF16-dDmoiMkTY:-OClexiY8hNj1YpFnu-7:bna947y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L89)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

triple slash for items docs
</blockquote></details>

what are item docs?
it's a sub routine, also a todo


<!-- Sent from Reviewable.io -->

2024-11-28 09:58 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 12 of 13 files reviewed, 9 unresolved discussions (waiting on @anatgstarkware, @ohad-starkware, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 66 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYyjX6cZvel6ToVW3:-OCm9Iwp19j0rkVnquAg:b-yzrb9d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L66)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

these changes are already merged
</blockquote></details>

Then a rebase is needed, I guess?
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 89 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYjtF16-dDmoiMkTY:-OCmBTvR4muau-VvT-UB:b-uxanut) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L89)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

what are item docs?
it's a sub routine, also a todo
</blockquote></details>

Sorry, my bad, triple only for the first line (and the TODO should be first)
"item docs" - I meant documentation of items (functions, traits, structs, enums, modules...). The triple slash makes the doc go to the popup you see when you hover over an item. double is good for e.g. documentation of logic inside functions, TODOs


<!-- Sent from Reviewable.io -->

2024-11-28 10:11 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 5 of 13 files reviewed, 7 unresolved discussions (waiting on @anatgstarkware, @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 67 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCic_nl3XDmnrEhJtiI:-OCm8j0d-vl3SbydQE2A:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L67)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I am not sure we want the whole trace in the log. Counts were somewhat concise and gave some info.
If you still want to have the whole trace and not the counts, the var should be renamed (and the log text).
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 14 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiWqsm5qEmroRFoTBI:-OCm4b8z0pNYGhR9eJHK:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/plain.rs#L14)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Please doc `generic_only` and when/why it should be used.
(and maybe the function if already here :) )
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/vm_runner/src/main.rs` line 101 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCicGhn9xIWK0AHid-W:-OCmBqGnDh1DJfsQQkdy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/vm_runner/src/main.rs#L101)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

We only want the counts as execution resources - why did you change it?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvcB79KeBdFWWNRQs:-OCm9XJa5HW303iExqbp:b-64pfb7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L164)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Unless I miss something, this struct represents a single transition of state. The plural name is confusing.
The doc better be singular too IMO
</blockquote></details>

It represents an entire program, consisting of multiple transitions from one CASM state to another (CASM state = pc, ap, fp).
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 13 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiXKhL7ni-jXgsDvAh:-OCm8m8Z6Ku-zdU4qjpq:b-3zja3r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L13)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

VmState or CasmState?
It holds `CasmState`s
</blockquote></details>

The name CasmState in prover typle will going to change to vmState
I will change to casmState for now...
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 59 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYJWzDGVi0FRJycYa:-OCmAQ-M6MULmP7AHrBl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L59)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Sorry for nitpicking, but this, OTOH should be plural. Otherwise it may be read like there is a single vm state belonging/matching any opcode.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 66 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiYyjX6cZvel6ToVW3:-OCmDhh-AP7h8Z7yK6Ul:b-7hrntz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L66)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Then a rebase is needed, I guess?
</blockquote></details>

Addede anyway


<!-- Sent from Reviewable.io -->

2024-11-28 14:07 UTC, yuvalsw reviewed
> Reviewed 6 of 8 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @anatgstarkware, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transition.rs` line 164 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCTvcB79KeBdFWWNRQs:-OCn33RZ02KavkNDpF8i:bu9qble) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f2b9d412223a67995cea56c1b83c1f5f50e5908c/stwo_cairo_prover/crates/prover/src/input/state_transition.rs#L164)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

It represents an entire program, consisting of multiple transitions from one CASM state to another (CASM state = pc, ap, fp).
</blockquote></details>

I thought of it as a transition from the initial state to the final state, with the details of what happens in the middle. But I get what you meant now, so I am ok with both options.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 12 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiX7QM9mzCvwo3qSaW:-OCn2jY29cnjxDXegV0d:b-qkoh5d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L12)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Serialize but not Deserialize on purpose?
</blockquote></details>

I meant we probably need both (or none)
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 58 at r13](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCn2ZU68nmF47GfND9_:-OCn2ZU68nmF47GfND9a:b-yzpttq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/590e94052a9a56f1dc940a3be4476b00a0733210/stwo_cairo_prover/crates/prover/src/input/plain.rs#L58)):*
> ```XML
> // TODO(yuval): consider returning a result instead of panicking...
> /// Assumes memory and trace are already relocated. Otherwise panics.
> // TODO(Ohad): remove dev_mode after adding the rest of the opcodes.
> ```

move the TODOs to before the item doc
___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 68 at r13](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCn4z491RTapjTjdwhq:-OCn4z4A9qTj--toMCaX:b3wtusm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/590e94052a9a56f1dc940a3be4476b00a0733210/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L68)):*
> ```XML
> 
>     let instruction_counts = &vm_output.state_transitions.casm_states_by_opcode.counts();
>     log::info!("Instruction counts: {instruction_counts:?}");
> ```

Consider rephrasing "instruction counts" now, but up to you (nonblocking)



_Code quote:_
```XML
"Instruction counts: {instruction_counts:?}");
```
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 187 at r13](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCn4M235ScMgNHTivW-:-OCn4M235ScMgNHTivW0:bu9ecrg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/590e94052a9a56f1dc940a3be4476b00a0733210/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L187)):*
> ```XML
>         res.push_instr(mem, first.into(), dev_mode);
> 
>         let mut last_element = first;
> ```

I missed some things here, so it's even easier. You don't need to keep track of last_element. You can just use `entry` in the if before the `break`. That would additionally save all the copies.
___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 201 at r13](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCn3p_h8gLbBcG8DQFa:-OCn3p_h8gLbBcG8DQFb:b-4cdcva) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/590e94052a9a56f1dc940a3be4476b00a0733210/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L201)):*
> ```XML
> 
>     /// Pushes the state transition at pc into the appropriate opcode component.
>     // TODO(Ohad): remove dev_mode after adding the rest of the instructions.
> ```

please move to before the item doc.


<!-- Sent from Reviewable.io -->

2024-11-28 15:35 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192)* status: 8 of 13 files reviewed, all discussions resolved (waiting on @anatgstarkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/state_transitions.rs` line 12 at r11](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-OCiX7QM9mzCvwo3qSaW:-OCnNtXW7tJ1aP9WS9XT:br5ogoh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/6a97f37ff8788b38d0c6212ffbc77a59d3bfae28/stwo_cairo_prover/crates/prover/src/input/state_transitions.rs#L12)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I meant we probably need both (or none)
</blockquote></details>

None...


<!-- Sent from Reviewable.io -->

2024-11-28 17:56 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/192#-:-OCnuf6xCTJCY-ozyUtX:bnfp4nl)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @anatgstarkware and @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-11-28 19:16 UTC, merged