Ci run large test
starkware-libs/stwo-cairo pull request #252
Opened 2024-12-16 11:39 UTC by Stavbe

Move big files to google cloud (delete the use of lfs)
Run large files test from ci

2024-12-16 13:39 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEfcRo9qyIIgpmYtWO:-OEEfcRp0KOqm--lXtLI:ba71ad) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/README.md#L4)):*
> ```Markdown
> ```
> This repo utilizes Google Cloud Storage for test artifacts. The test artifacts can be found and modified at the following URL:
> https://console.cloud.google.com/storage/browser/stwo-cairo-testing-artifacts?project=starkware-thirdparties
> ```

It's best to put this info next to the test, and delete the false information from the main README
also doc how to add new tests



_Code quote:_
```Markdown
https://console.cloud.google.com/storage/browser/stwo-cairo-testing-artifacts?project=starkware-thirdparties
```
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEeh6R7HOwW2FxO3AK:-OEEeh6R7HOwW2FxO3AL:b-krpxfy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L4)):*
> ```Shell
> 
> BUCKET_URL="https://storage.googleapis.com/stwo-cairo-testing-artifacts"
> DEST_DIR="crates/prover/test_data"
> ```

is it in .gitignore?
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEf-Aq7LzYEfNkBHoj:-OEEf-Aq7LzYEfNkBHok:bbeyiyz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L5)):*
> ```Shell
> BUCKET_URL="https://storage.googleapis.com/stwo-cairo-testing-artifacts"
> DEST_DIR="crates/prover/test_data"
> TEST_NAME="test_read_from_large_files"
> ```

imo this should not be specified, 
pull everything and cargo test --features="some_name" 
functions tagged with that feature should expect their storage to sit in stwo-cairo-testing-artifacts
basically- it should be easy to add new tests
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 31 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEfLpp59QULbvreYZO:-OEEfLpp59QULbvreYZP:b-kv9ehy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L31)):*
> ```Shell
> # Delete the downloaded files
> echo "Cleaning up downloaded files..."
> rm -rf "${DEST_DIR}/${TEST_NAME}"*
> ```

Sometimes I would like not to clean,
like when I am running locally


<!-- Sent from Reviewable.io -->

2024-12-16 15:45 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 31 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEfLpp59QULbvreYZO:-OEF8D0VD6CUF3JFoC4U:bx8uuza) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L31)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Why not? You can understand what is written there anyway, and it's easier to not delete manually before commit changes.
</blockquote></details>

can't...


<!-- Sent from Reviewable.io -->

2024-12-16 15:59 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEeh6R7HOwW2FxO3AK:-OEFAya48AR57qWoDCQZ:b-5hvn1y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L4)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

The other script not there on purpoose?
</blockquote></details>

I meant the directory written in that line
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEf-Aq7LzYEfNkBHoj:-OEFB1pT2geZ3K9Uy02m:bpn2j6s) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L5)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

I was trying to do so but the ci didn't like the fetaure header in the toml.
Let's begin with a simpler version?
</blockquote></details>

yes unless you can fix it quick then ill be ok with it here because --ignored is wrong (we have ignored tests that wont pass, or shouldn't i.e. the small mull)
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 31 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEfLpp59QULbvreYZO:-OEFBEDz8ER7PK6MXGBm:b-lnao0d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L31)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

can't...
</blockquote></details>

if the folder is git ignored then you never have to remove, download once and work with it.
if I'm on the train I can't run tests? unplesent...


<!-- Sent from Reviewable.io -->

2024-12-16 16:00 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEf-Aq7LzYEfNkBHoj:-OEFBh-J4j8i2VvsHtyO:bcqicds) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L5)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes unless you can fix it quick then ill be ok with it here because --ignored is wrong (we have ignored tests that wont pass, or shouldn't i.e. the small mull)
</blockquote></details>

and for the TEST_NAME var, just remove it and download everything from the cloud folder no?


<!-- Sent from Reviewable.io -->

2024-12-19 17:10 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEfcRo9qyIIgpmYtWO:-OEUjZvk7D9yH80uvDOt:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/README.md#L4)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

It's best to put this info next to the test, and delete the false information from the main README
also doc how to add new tests
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 4 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEeh6R7HOwW2FxO3AK:-OEUk6dXBmDAQnuCuB3s:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L4)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I meant the directory written in that line
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 5 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEf-Aq7LzYEfNkBHoj:-OEUk6So7h--pfdh0Oer:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L5)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

and for the TEST_NAME var, just remove it and download everything from the cloud folder no?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/scripts/run_large_test.sh` line 31 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEEfLpp59QULbvreYZO:-OEUkFCA8crTQIikZFgO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/df2163081db015563e4b55b1faab275998f762d2/stwo_cairo_prover/scripts/run_large_test.sh#L31)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

if the folder is git ignored then you never have to remove, download once and work with it.
if I'm on the train I can't run tests? unplesent...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-19 17:53 UTC, shaharsamocha7 requested changes
> Reviewed 5 of 13 files at r1, 7 of 10 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 16 of 17 files reviewed, 10 unresolved discussions (waiting on @ohad-starkware and @Stavbe)

___
*[`.github/workflows/cairo-ci.yaml` line 41 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUyFJz6mR6Hx6gXGGw:-OEUyFK-6OyAy0bv1hYi:bcrl73g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7b89d3766dce63138235bd652f21c0a9291d358c/.github/workflows/cairo-ci.yaml#L41)):*
> ```YAML
>       - uses: actions/checkout@v3
>         with:
>           lfs: false
> ```

Remove the lfs related thing



_Code quote:_
```YAML
        with:
          lfs: false
```
___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEV2CXBDad4fx-4i3rn:b-7xahma) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> BUCKET_URL="https://storage.googleapis.com/stwo-cairo-testing-artifacts"
> ```

Is this code safe to use?
It downloads all the files in that URL



_Code quote:_
```Shell
BUCKET_URL="https://storage.googleapis.com/stwo-cairo-testing-artifacts"
```
___
*[`.github/workflows/cairo-ci.yaml` line 49 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUyXxq32l6XaInz16G:-OEUyXxq32l6XaInz16H:b-iavwy2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/.github/workflows/cairo-ci.yaml#L49)):*
> ```YAML
>           toolchain: nightly-2024-12-16
>       - uses: Swatinem/rust-cache@v2
>       - run: cargo +nightly-2024-12-16 test --release --features slow-test
> ```

Nit: Consider to rename



_Suggestion:_
```YAML
slow-tests
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUyqv5CZ5tKKiQNpuE:-OEUyqv5CZ5tKKiQNpuF:b-a6i4s8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L136)):*
> ```XML
>     // To run the tests, use:
>     // `cargo test test_read_from_large_files --features "ci-test" `
>     // `cargo test test_read_from_small_file --features "ci-test" `
> ```

Rename
(Or slow-tests as suggested above)



_Suggestion:_
```XML
    // `cargo test test_read_from_large_files --features "slow-test" `
    // `cargo test test_read_from_small_file --features "slow-test" `
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 239 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUzKVC3Js6c5fqLMjK:-OEUzCANBE0woqUxEe6p:b-bd5k1o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L239)):*
> ```XML
>     }
> 
>     // When not ignored, the test passes only with dev_mod = false.
> ```

Fix the prefix of the sentence
@ohad-starkware is this comment still relevant?
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUz2cN6WqOx01l3Swr:-OEUz2cN6WqOx01l3Sws:b-jwfmu9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7b89d3766dce63138235bd652f21c0a9291d358c/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L158)):*
> ```XML
>     fn test_read_from_large_files() {
>         let input = large_cairo_input();
>         let components = input.state_transitions.casm_states_by_opcode;
> ```

Fix error message



_Code quote:_
```XML
        import_from_vm_output(d.join("pub.json").as_path(), d.join("priv.json").as_path()).expect(
            "
            Failed to read test files. Maybe git-lfs is not installed? Checkout README.md.",
        )
```


<!-- Sent from Reviewable.io -->

2024-12-22 07:43 UTC, ohad-starkware commented
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEhJQJt8-pJxSD1WOh-:b-to5866) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this code safe to use?
It downloads all the files in that URL
</blockquote></details>

I asked for that, the link is public but contents are controlled by sw, is that a problem?


<!-- Sent from Reviewable.io -->

2024-12-22 07:45 UTC, ohad-starkware commented
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEhJtQG1gt4_3XrRbO-:b3uanul) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I asked for that, the link is public but contents are controlled by sw, is that a problem?
</blockquote></details>

but maybe specify the project 
https://storage.googleapis.com/stwo-cairo-testing-artifacts?project=starkware-thirdparties


<!-- Sent from Reviewable.io -->

2024-12-22 07:46 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 16 of 17 files reviewed, 7 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 239 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUzKVC3Js6c5fqLMjK:-OEhJ5prCLf-I7l5Xj4_:buhlbud) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L239)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix the prefix of the sentence
@ohad-starkware is this comment still relevant?
</blockquote></details>

yes, dev_mode is waiting on mul_small to be implemented without rc3 
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 128 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEhJh7v0Ky7vq0iwRyK:-OEhJh7w6BT8ahfAytQm:bnt1zau) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L128)):*
> ```XML
> pub mod tests {
> 
>     // Those tests utilize Google Cloud Storage for the input:
> ```

this doc belongs in a README.md somewhere, maybe under input? 


<!-- Sent from Reviewable.io -->

2024-12-22 12:37 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 13 of 18 files reviewed, 6 unresolved discussions (waiting on @ohad-starkware, @shaharsamocha7, and @Stavbe)

___
*[`.github/workflows/cairo-ci.yaml` line 41 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUyFJz6mR6Hx6gXGGw:-OEiMdn3Ctr-6DyLRPSI:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7b89d3766dce63138235bd652f21c0a9291d358c/.github/workflows/cairo-ci.yaml#L41)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove the lfs related thing
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 128 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEhJh7v0Ky7vq0iwRyK:-OEiMlxQ0ELJ-Th84iU_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L128)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this doc belongs in a README.md somewhere, maybe under input?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 136 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUyqv5CZ5tKKiQNpuE:-OEiMq7P2D-QlcsjgrXD:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L136)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename
(Or slow-tests as suggested above)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 158 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUz2cN6WqOx01l3Swr:-OEiMtyn7mlR8ZqqO2pM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7b89d3766dce63138235bd652f21c0a9291d358c/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L158)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Fix error message
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 239 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUzKVC3Js6c5fqLMjK:-OEi7tPI5_gDuxS8i3zC:brycrst) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L239)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

yes, dev_mode is waiting on mul_small to be implemented without rc3
</blockquote></details>

This is removed in 245.
___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEi8WTD2J905G3S7UQX:bdpoye7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

but maybe specify the project 
https://storage.googleapis.com/stwo-cairo-testing-artifacts?project=starkware-thirdparties
</blockquote></details>

1. That's what Alon Dotan offered us to use.
2. Not possible to specify the project name in the storge url, but:
"Bucket names in Google Cloud are globally unique, so there is no ambiguity when accessing a bucket. Including the project name is unnecessary for addressing."


<!-- Sent from Reviewable.io -->

2024-12-22 13:06 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 13 of 18 files reviewed, 14 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 5 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSc4q2K1Cx3wakwsj:-OEiSc4q2K1Cx3wakwsk:b-piegb9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L5)):*
> ```Markdown
> ## Input Files
> 
> The input files for the tests in vm_import are stored in Google Cloud Storage:  
> ```

remove line
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 8 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSflo7q3tHHwizQq2:-OEiSehM0sK1WjtzTbKT:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L8)):*
> ```Markdown
> [Google Cloud Storage Browser](https://console.cloud.google.com/storage/browser/stwo-cairo-testing-artifacts?project=starkware-thirdparties)
> 
> ## How to Run the Tests
> ```





_Suggestion:_
```Markdown
## How to Tests
```
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 10 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSlCVDdXUDldhG2IS:-OEiSlCVDdXUDldhG2IT:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L10)):*
> ```Markdown
> ## How to Run the Tests
> 
> 1. **Download Input Files**  
> ```





_Suggestion:_
```Markdown
**Download Tests Files*
```
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 11 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSiVb-9PJ1NbeDsed:-OEiSiVb-9PJ1NbeDsee:bvtkv1g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L11)):*
> ```Markdown
> 
> 1. **Download Input Files**  
>    Run the following script to fetch the required input files from Google Cloud Storage:
> ```

delete line
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 17 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSoNk81BF4eygXqKn:-OEiSoNk81BF4eygXqKo:bvtkv1g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L17)):*
> ```Markdown
> 
> 2. **Execute Tests**  
>    Use the following commands to run the tests:
> ```

delete line
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 26 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiT1hG9Vd4lxeQDxzW:-OEiT1hG9Vd4lxeQDxzX:b-a3gdbx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L26)):*
> ```Markdown
> 
> These tests are configured to run automatically in the CI pipeline.  
> However, note that they will be ignored unless the `--features "slow-tests"` flag is specified in the `cargo test` command.
> ```

this is clear from the instructions above and below
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 33 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiTGSE1qPvRz7p7vSe:-OEiTGSE1qPvRz7p7vSf:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L33)):*
> ```Markdown
>    Create a new directory at the Google Cloud Storage URL above and add the required files.
> 
> 2. **Automated Download**  
> ```

remove
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 39 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiTJVt0SmT8F50s1Wl:-OEiTJVt0SmT8F50s1Wm:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L39)):*
> ```Markdown
>    Mark the new test with `#[cfg(feature = "slow-tests")]` to ensure it runs in the CI pipeline.
> 
> 4. **Make Sure the Test Passes Locally**  
> ```





_Suggestion:_
```Markdown
*Run Tests Locally**
```


<!-- Sent from Reviewable.io -->

2024-12-22 13:06 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 37 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiTQkD6zcF1jYTR886:-OEiTQkD6zcF1jYTR887:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L37)):*
> ```Markdown
> 
> 3. **Mark the Test**  
>    Mark the new test with `#[cfg(feature = "slow-tests")]` to ensure it runs in the CI pipeline.
> ```





_Suggestion:_
```Markdown
Mark the new test with `#[cfg(feature = "slow-tests")]`.
```


<!-- Sent from Reviewable.io -->

2024-12-22 13:07 UTC, ohad-starkware commented
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEiTgeRAQKjkQKf_fEC:b-s4s3gs) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

1. That's what Alon Dotan offered us to use.
2. Not possible to specify the project name in the storge url, but:
"Bucket names in Google Cloud are globally unique, so there is no ambiguity when accessing a bucket. Including the project name is unnecessary for addressing."
</blockquote></details>

coolio


<!-- Sent from Reviewable.io -->

2024-12-22 13:07 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 13 of 18 files reviewed, 14 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 239 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUzKVC3Js6c5fqLMjK:-OEiTYAA-9YL9qxFeETF:b-vdu1g5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L239)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

This is removed in 245.
</blockquote></details>

https://graphite.dev/docs/graphite-cli


<!-- Sent from Reviewable.io -->

2024-12-22 13:44 UTC, Stavbe commented
* **#252** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/252?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/252?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-22 13:47 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 13 of 18 files reviewed, 14 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 5 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSc4q2K1Cx3wakwsj:-OEibHyr2b77fIvMbsxO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L5)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove line
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 11 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSiVb-9PJ1NbeDsed:-OEibM0eD9-6Eq5IqBrP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L11)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

delete line
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 17 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSoNk81BF4eygXqKn:-OEibMD85IWofIjnVfB9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L17)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

delete line
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 26 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiT1hG9Vd4lxeQDxzW:-OEibNHc85yckjqLJepQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L26)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this is clear from the instructions above and below
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 33 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiTGSE1qPvRz7p7vSe:-OEibSQKCFfR75lNPgqQ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L33)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 239 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEUzKVC3Js6c5fqLMjK:-OEiZPUjBuSWAr9H0J_J:b-x6515k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L239)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

https://graphite.dev/docs/graphite-cli
</blockquote></details>

On it :)
___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEibWTk4RLsizYgYvao:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

coolio
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 8 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSflo7q3tHHwizQq2:-OEibK1y0RofdtlOguu4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L8)):*
> ```Markdown
> [Google Cloud Storage Browser](https://console.cloud.google.com/storage/browser/stwo-cairo-testing-artifacts?project=starkware-thirdparties)
> 
> ## How to Run the Tests
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 10 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiSlCVDdXUDldhG2IS:-OEibL2C5WA876THxCgO:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L10)):*
> ```Markdown
> ## How to Run the Tests
> 
> 1. **Download Input Files**  
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 39 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEiTJVt0SmT8F50s1Wl:-OEiZ8VG0fK5bsxF4Sib:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/4209c7dc3796a18dc35da89e5e79ce8441052877/stwo_cairo_prover/crates/prover/src/input/README.md#L39)):*
> ```Markdown
>    Mark the new test with `#[cfg(feature = "slow-tests")]` to ensure it runs in the CI pipeline.
> 
> 4. **Make Sure the Test Passes Locally**  
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-22 14:11 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 10 files at r4, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-:-OEihGL1000g3QzXvu8W:bnfp4nl)* status: 15 of 18 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-12-24 10:26 UTC, shaharsamocha7 approved these changes
> Reviewed 2 of 4 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: all files reviewed, 1 unresolved discussion (waiting on @Stavbe)

___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEsBiUt9g6zTOeQmvKF:brgn867) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IDK if this is a problem.
Should we ask someone? I don't want to tag HaimK
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 230 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEsBU6a1LtjV6jqaY_S:-OEsBU6a1LtjV6jqaY_T:b-7jc0as) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef4680dd9bc5addc6a74874ddb484263692235b8/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L230)):*
> ```XML
>     }
> 
>     // TODO (Stav): Once all the components are in, verify the proof to ensure the sort was correct.
> ```

sort?



_Code quote:_
```XML
 verify the proof to ensure the sort was correct.
```


<!-- Sent from Reviewable.io -->

2024-12-24 15:06 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: all files reviewed, 1 unresolved discussion (waiting on @Stavbe)

___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEtC9Gk1YCdqJ9nPhao:b-hx3za) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

IDK if this is a problem.
Should we ask someone? I don't want to tag HaimK
</blockquote></details>

lotem said it's ok


<!-- Sent from Reviewable.io -->

2024-12-24 16:04 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: all files reviewed, 1 unresolved discussion (waiting on @Stavbe)

___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 3 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OEV2CXBDad4fx-4i3rm:-OEtPLvr7R83IboLb6mq:b-nt43aj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1fdcb243144a367a89e22ee0660b39463df26fd3/stwo_cairo_prover/scripts/fetch_large_files.sh#L3)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

lotem said it's ok
</blockquote></details>

I asked Haim and he is checking


<!-- Sent from Reviewable.io -->

2024-12-26 16:41 UTC, Stavbe reviewed
Haim asked to specify the files, and mention this directory is external.
Ptal again :)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-:-OF2lAw77ntyNvx__W5r:bplc16j)* status: 14 of 19 files reviewed, all discussions resolved (waiting on @ohad-starkware, @shaharsamocha7, and @Stavbe)



<!-- Sent from Reviewable.io -->

2024-12-26 17:02 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 22 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2ukW81NOurj2Yp60V:-OF2ukW81NOurj2Yp60W:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef4680dd9bc5addc6a74874ddb484263692235b8/stwo_cairo_prover/crates/prover/src/input/README.md#L22)):*
> ```Markdown
> 1. **Create a Directory**  
>    Create a new directory at the Google Cloud Storage URL above and add the required files.
> ```





_Suggestion:_
```Markdown
Create a new folder at the Cloud Storage URL above and upload the necessary files.
```


<!-- Sent from Reviewable.io -->

2024-12-26 17:04 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 14 of 19 files reviewed, 5 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 165 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2u7u78idonJoS-I7t:-OF2u7u78idonJoS-I7u:b-z53czg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L165)):*
> ```XML
>     }
> 
>     // TODO (Stav): Once all the components are in, verify the proof to ensure the adapter works
> ```

I don't agree with this comment, this is a read test, not a prove test.
it's not the adapters job to prove, these tests should exist but somewhere else.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 233 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2tw591qdXuGUYLWe6:-OF2tw591qdXuGUYLWe7:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L233)):*
> ```XML
>     }
> 
>     // TODO (Stav): Once all the components are in, verify the proof to ensure the adapter works
> ```

same
___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 32 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2teDH3iaX5HlHFuic:-OF2teDH3iaX5HlHFuid:bk0nug) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/scripts/fetch_large_files.sh#L32)):*
> ```Shell
> done
> 
> echo "All specified files have been downloaded."
> ```

you are going to run this in a loop
echo something more descriptive, with the specific input given
___
*[`stwo_cairo_prover/scripts/slow_tests.json` line 1 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2vHH85kqIoj2z_zue:-OF2vHH85kqIoj2z_zuf:bb7lbs2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/scripts/slow_tests.json#L1)):*
> ```JSON
> {
> ```

nice
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 16 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2v7G40d6IJC6r-NwK:-OF2v7G40d6IJC6r-NwL:b-mqvtb2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef4680dd9bc5addc6a74874ddb484263692235b8/stwo_cairo_prover/crates/prover/src/input/README.md#L16)):*
> ```Markdown
>    cargo test test_read_from_large_files --features "slow-tests"
>    cargo test test_read_from_small_file --features "slow-tests"
>    ```
> ```

fine grained testing is specified below



_Suggestion:_
```Markdown
   cargo test --features "slow-tests"
```
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 10 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2u_3g4DZGkTq50Umi:-OF2u_3g4DZGkTq50Umj:b478m4m) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/crates/prover/src/input/README.md#L10)):*
> ```Markdown
> 1. **Download Tests Files**  
>    ```bash
>    ./scripts/fetch_large_files.sh
> ```

this will fail, right?


<!-- Sent from Reviewable.io -->

2024-12-29 09:20 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252)* status: 14 of 19 files reviewed, 5 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 16 at r8](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2v7G40d6IJC6r-NwK:-OFGdtwN7g_ToPSv3j7V:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/ef4680dd9bc5addc6a74874ddb484263692235b8/stwo_cairo_prover/crates/prover/src/input/README.md#L16)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

fine grained testing is specified below
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/README.md` line 10 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2u_3g4DZGkTq50Umi:-OFGgLI2Cj1DplSdPvIj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/crates/prover/src/input/README.md#L10)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this will fail, right?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 233 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2tw591qdXuGUYLWe6:-OFGep5l6E7cG_DI8SHu:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L233)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 32 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2teDH3iaX5HlHFuic:-OFGhmCD57ebguNsEuNc:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/scripts/fetch_large_files.sh#L32)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you are going to run this in a loop
echo something more descriptive, with the specific input given
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-29 09:43 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r10, 2 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-:-OFGn4ux23LTKlBsYHv3:bnfp4nl)* status: 17 of 19 files reviewed, all discussions resolved (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/scripts/fetch_large_files.sh` line 32 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/252#-OF2teDH3iaX5HlHFuic:-OFGn34A8oCffOEt9YyX:bb7lbs2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a4d75fd6f3ab66944c788de6b155f364310ec3ee/stwo_cairo_prover/scripts/fetch_large_files.sh#L32)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nice


<!-- Sent from Reviewable.io -->

2024-12-30 09:09 UTC, merged