delete redudent struct from json.rs
starkware-libs/stwo-cairo pull request #268
Opened 2024-12-19 12:15 UTC by Stavbe

2024-12-19 14:08 UTC, yuvalsw requested changes
Thanks for the cleanup!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-:-OEUBF744-oYRTrqSgjb:b-7dax7)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUDIZS23MnY-g9FmgP:-OEUDIZS23MnY-g9FmgQ:bmjaucu) (no related file):*
There are differences in the structs from LC's repo and the ones you deleted here in types of integers (usize in LC and u32/u64 here). This might be delicate sometimes. Did you make sure there is no scenario in which this change is significant?

One thing we'll have to do is to run an e2e test before merging this PR.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUBkogAODI9Nj8mKvV:-OEUBkogAODI9Nj8mKvW:b-uvwwvt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9674ad7fa7aa5b1247e42e8e7164a0438a595b6/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L35)):*
> ```XML
>     let _span = span!(Level::INFO, "import_from_vm_output").entered();
>     let pub_data_string = std::fs::read_to_string(pub_json)?;
>     let pub_data: PublicInput<'_> = sonic_rs::from_str(&pub_data_string)?;
> ```

is this `<'_>` required?



_Code quote:_
```XML
PublicInput<'_>
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUAo9t9iK5QYaYBh2E:-OEUAo9t9iK5QYaYBh2F:bdyarjv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9674ad7fa7aa5b1247e42e8e7164a0438a595b6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L7)):*
> ```XML
> type RangeCheckData = PrivateInputValue;
> 
> // Can't use AirPrivateInputSerializable since trace_path and mem_path are private.
> ```

1. better specify which (or in this case, from what repo) AirPrivateInputSerializable you refer to.
2. Not in this PR, but I think it's worth sending a PR to LC to change that
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUEGXlCNZbjfYyLAte:-OEUEGXlCNZbjfYyLAtf:bx5514i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/53c4ea9efb29a3c74c6c82626ee29efec22f1ec6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L51)):*
> ```XML
> 
> #[derive(Clone, Debug)]
> pub struct FeltValue([u8; 32]);
> ```

The equivalent type used in LC's repo is starknet_types_core::felt::Felt which is implemented differently. Did you verify this difference is not important here?


<!-- Sent from Reviewable.io -->

2024-12-19 17:27 UTC, Stavbe reviewed
It made your life harder, don’t deny it.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-:-OEUwxcs0ssdQf8hqg-M:b-a5gtkh)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @yuvalsw)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUDIZS23MnY-g9FmgP:-OEUHnHm6JbcF4d8T-IO:b-8ij99v) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

There are differences in the structs from LC's repo and the ones you deleted here in types of integers (usize in LC and u32/u64 here). This might be delicate sometimes. Did you make sure there is no scenario in which this change is significant?

One thing we'll have to do is to run an e2e test before merging this PR.
</blockquote></details>

The data is output from the VM using the LC types. That’s why I feel it’s not risky, but even more accurate to use the original types and make a conversion if needed.  There is no use for this code, so I can’t understand the intention behind creating it,
but I suspect it was part of some POC.  
If you think it’s too risky, we can leave it as is.

WDYT @shaharsamocha7 ?
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUAo9t9iK5QYaYBh2E:-OEUoP0dChtMHElnQHK8:b-u202k5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9674ad7fa7aa5b1247e42e8e7164a0438a595b6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L7)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. better specify which (or in this case, from what repo) AirPrivateInputSerializable you refer to.
2. Not in this PR, but I think it's worth sending a PR to LC to change that
</blockquote></details>

1. Done
2. The problem is that I’m not sure if it’s intentional, and I couldn’t find anyone who can verify that I won’t be accused of breaking the vm security.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUEGXlCNZbjfYyLAte:-OEUpX9X-LqjBMuzTfvQ:b-imvtr8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/53c4ea9efb29a3c74c6c82626ee29efec22f1ec6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

The equivalent type used in LC's repo is starknet_types_core::felt::Felt which is implemented differently. Did you verify this difference is not important here?
</blockquote></details>

Well, I didn’t find a use for this, so I can’t be 100% sure... But note that VM outputs the data using the type `starknet_types_core::felt::Felt`, and I noticed there are functions that can convert it to `[u8; 32]` in the  impl of `FieldElement<Stark252PrimeField>`, so I don't see a good reason to keep it.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUBkogAODI9Nj8mKvV:-OEUuPjq6EJzPBLuW4kI:bmsh22z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9674ad7fa7aa5b1247e42e8e7164a0438a595b6/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L35)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this `<'_>` required?
</blockquote></details>

Yes.. Clippy : error: hidden lifetime parameters in types are deprecated


<!-- Sent from Reviewable.io -->

2024-12-19 19:09 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @Stavbe and @yuvalsw)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUDIZS23MnY-g9FmgP:-OEVBWvICD2_MZ6b-XsP:b-ze4o1q) (no related file):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

The data is output from the VM using the LC types. That’s why I feel it’s not risky, but even more accurate to use the original types and make a conversion if needed.  There is no use for this code, so I can’t understand the intention behind creating it,
but I suspect it was part of some POC.  
If you think it’s too risky, we can leave it as is.

WDYT @shaharsamocha7 ?
</blockquote></details>

I think that first we need to decide if we want to keep this flow or discard it.
If yes, we need to make this code support all the builtins and add tests.
If not, why not remove all of it?
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEVGy1T60lis7kuQKU5:-OEVGy1T60lis7kuQKU6:b-ps035g) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b366d048daf859ec2de0ae5557ac7affba3987bd/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L7)):*
> ```XML
> type RangeCheckData = PrivateInputValue;
> 
> // Can't use cairo_vm::air_private_input::AirPrivateInputSerializable since trace_path and mem_path
> ```

Note: you can use a link to code with ``



_Code quote:_
```XML
cairo_vm::air_private_input::AirPrivateInputSerializable
```


<!-- Sent from Reviewable.io -->

2024-12-22 10:16 UTC, yuvalsw requested changes
I neither confirm nor deny

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-:-OEhrT-qBAzjGl4iL2rX:b-i9kkkc)* status: all files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @Stavbe)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUDIZS23MnY-g9FmgP:-OEhnxZ37egO7ajMTsWq:b-pcd3my) (no related file):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think that first we need to decide if we want to keep this flow or discard it.
If yes, we need to make this code support all the builtins and add tests.
If not, why not remove all of it?
</blockquote></details>

Stav - makes sense, thanks.
Shahar - what flow do you refer to? Anyway, this PR only removes unused stuff and aligns things better with the VM - is there a downside to it? If we later can remove more code - we will.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUAo9t9iK5QYaYBh2E:-OEhmu9o6pSyqINQ5o-3:bgy99yj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9674ad7fa7aa5b1247e42e8e7164a0438a595b6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L7)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

1. Done
2. The problem is that I’m not sure if it’s intentional, and I couldn’t find anyone who can verify that I won’t be accused of breaking the vm security.
</blockquote></details>

2. pub only changes the access control to these fields. The vm itself will still have the exact same logic. It can only "break" something if later used somewhere where it shouldn't have been. Anyway, if it's super important to LC, they can say it in the review. In that case, we probably also want to know why (maybe it applies to us too?). But I really think it's not.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUEGXlCNZbjfYyLAte:-OEhql3B-upe2gwGNekw:b-806bjg) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/53c4ea9efb29a3c74c6c82626ee29efec22f1ec6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L51)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Well, I didn’t find a use for this, so I can’t be 100% sure... But note that VM outputs the data using the type `starknet_types_core::felt::Felt`, and I noticed there are functions that can convert it to `[u8; 32]` in the  impl of `FieldElement<Stark252PrimeField>`, so I don't see a good reason to keep it.
</blockquote></details>

OK, sounds right. Can you point to this impl though? I couldn't find it.


<!-- Sent from Reviewable.io -->

2024-12-22 13:16 UTC, Stavbe commented
* **#268** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/268?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/268?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-22 15:46 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @shaharsamocha7 and @yuvalsw)

___
*[a discussion](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUDIZS23MnY-g9FmgP:-OEiqYtg1pBsD2P-RU55:bd1uufd) (no related file):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Stav - makes sense, thanks.
Shahar - what flow do you refer to? Anyway, this PR only removes unused stuff and aligns things better with the VM - is there a downside to it? If we later can remove more code - we will.
</blockquote></details>

He meant that if we decide to clean it, we need to remove all the unnecessary fields. I left only the two private fields, added a TODO to delete them, and opened a PR in the LC repository.

Regarding testing `test_read_from_small_files` and `test_read_from_large_files` pass (both use the `import_from_vm_output` function that changed).

To my understanding, the Cairo input will only need the memory section addresses of the builtins - so the changes of the other types won't affect anything.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUAo9t9iK5QYaYBh2E:-OEiztt81Qyh1DJmIs_2:b-6d3uri) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9674ad7fa7aa5b1247e42e8e7164a0438a595b6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L7)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

2. pub only changes the access control to these fields. The vm itself will still have the exact same logic. It can only "break" something if later used somewhere where it shouldn't have been. Anyway, if it's super important to LC, they can say it in the review. In that case, we probably also want to know why (maybe it applies to us too?). But I really think it's not.
</blockquote></details>

Yes. working on it, added a todo
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEUEGXlCNZbjfYyLAte:-OEj1w2bEl5q1PV-HNQi:bo6v5yx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/53c4ea9efb29a3c74c6c82626ee29efec22f1ec6/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L51)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

OK, sounds right. Can you point to this impl though? I couldn't find it.
</blockquote></details>

to_bites_be() in /starknet-types-core-0.1.7/src/felt/mod.rs
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEVGy1T60lis7kuQKU5:-OEj-B_04EAZbCqGeLMr:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b366d048daf859ec2de0ae5557ac7affba3987bd/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Note: you can use a link to code with ``
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-23 05:53 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-:-OEm4-fRAsws2SVBVrqP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-12-23 07:57 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268)* status: all files reviewed, 2 unresolved discussions (waiting on @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEmWBOL9XaBrFighrWF:-OEmWBOL9XaBrFighrWG:blsiu57) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c9396ddb50a3d7afb92961a35895559f4bf6973/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L37)):*
> ```XML
>     let _span = span!(Level::INFO, "import_from_vm_output").entered();
>     let pub_data_string = std::fs::read_to_string(pub_json)?;
>     let pub_data: PublicInput<'_> = sonic_rs::from_str(&pub_data_string)?;
> ```

Revert this change



_Code quote:_
```XML
    let pub_data_string = std::fs::read_to_string(pub_json)?;
    let pub_data: PublicInput<'_> = sonic_rs::from_str(&pub_data_string)?;
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-OEmVJ_p5AvO-NxVTH4W:-OEmVJ_p5AvO-NxVTH4X:bjii05v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/5c9396ddb50a3d7afb92961a35895559f4bf6973/stwo_cairo_prover/crates/prover/src/input/vm_import/json.rs#L3)):*
> ```XML
> use serde::{Deserialize, Serialize};
> // TODO(Stav): delete this struct after making those fieldes public in
> // `vm::air_private_input::AirPrivateInputSerializable.
> ```

I think you should also add a doc to this struct, besides for the TODO
Suggested down



_Suggestion:_
```XML
// Struct to store Cairo private input.
// Replicated from `cairo_vm::air_private_input::AirPrivateInputSerializable`
// TODO(Stav): Replace with original struct once fields are public.
```


<!-- Sent from Reviewable.io -->

2024-12-23 13:05 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/268#-:-OEnbk0GBp57IUedR31A:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Stavbe)



<!-- Sent from Reviewable.io -->

2024-12-23 13:23 UTC, merged