support builtins in the adapter
starkware-libs/stwo-cairo pull request #269
Opened 2024-12-19 13:05 UTC by Stavbe

2024-12-19 14:45 UTC, ohad-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @DavidLevitGurevich and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUG6eR-GuIX2lcih62:-OEUG6eR-GuIX2lcih63:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L5)):*
> ```XML
> use cairo_vm::air_public_input::MemorySegmentAddresses;
> 
> // TODO(STAV): Understand if the adapter should pass builtins that won't be supported by stwo.
> ```





_Suggestion:_
```XML
TODO(Stav)
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUHstd9GzW2PSNKNFD:-OEUHstd9GzW2PSNKNFE:bzp6lc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L10)):*
> ```XML
> #[derive(Debug)]
> pub struct BuiltinsSegments {
>     pub range_check_bits_128_builtin: MemorySegmentAddresses,
> ```

struct represents only buildtins, no need to mention that
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUI-wQ85YblwlR6Ifw:-OEUI-wQ85YblwlR6Ifx:b-yxq2su) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L22)):*
> ```XML
> }
> 
> impl Default for BuiltinsSegments {
> ```

please remove that
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 136 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUIoR59ltEx1ZJTVZY:-OEUIoR59ltEx1ZJTVZZ:bb7phvt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L136)):*
> ```XML
>                     }
>                 }
>                 // Output, executaion and program segments are not builtins.
> ```

typo
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEULfA819dw2v4brSAA:-OEULfA819dw2v4brSAB:bvyb82y) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L144)):*
> ```XML
>         }
>         res
>     }
> ```

better?



_Suggestion:_
```XML
pub struct BuiltinsSegments {
    pub range_check_bits_128_builtin: Option<MemorySegmentAddresses>,
    pub range_check_bits_96_builtin: Option<MemorySegmentAddresses>,
    pub bitwise_builtin: Option<MemorySegmentAddresses>,
    pub add_mod_builtin: Option<MemorySegmentAddresses>,
    pub ec_op_builtin: Option<MemorySegmentAddresses>,
    pub ecdsa_builtin: Option<MemorySegmentAddresses>,
    pub keccak_builtin: Option<MemorySegmentAddresses>,
    pub mul_mod_builtin: Option<MemorySegmentAddresses>,
    pub pedersen_builtin: Option<MemorySegmentAddresses>,
    pub poseidon_builtin: Option<MemorySegmentAddresses>,
}
impl BuiltinsSegments {
    /// Create a new `BuiltinsSegments` struct from a map of memory MemorySegmentAddressess.
    pub fn from_memory_segments(
        memory_segments: &HashMap<&str, cairo_vm::air_public_input::MemorySegmentAddresses>,
    ) -> Self {
        let mut res = BuiltinsSegments::default();
        for (name, value) in memory_segments.iter() {
            match *name {
                "range_check" => {
                    res.range_check_bits_128_builtin =
                        Some((value.begin_addr, value.stop_ptr).into())
                }

                "range_check96" => {
                    res.range_check_bits_96_builtin =
                        Some((value.begin_addr, value.stop_ptr).into())
                }
                "bitwise" => res.bitwise_builtin = Some((value.begin_addr, value.stop_ptr).into()),
                "add_mod" => res.add_mod_builtin = Some((value.begin_addr, value.stop_ptr).into()),
                "ec_op" => res.ec_op_builtin = Some((value.begin_addr, value.stop_ptr).into()),
                "ecdsa" => res.ecdsa_builtin = Some((value.begin_addr, value.stop_ptr).into()),
                "keccak" => res.keccak_builtin = Some((value.begin_addr, value.stop_ptr).into()),
                "mul_mod" => res.mul_mod_builtin = Some((value.begin_addr, value.stop_ptr).into()),
                "pedersen" => {
                    res.pedersen_builtin = Some((value.begin_addr, value.stop_ptr).into())
                }
                "poseidon" => {
                    res.poseidon_builtin = Some((value.begin_addr, value.stop_ptr).into())
                }

                // Output, executaion and program segments are not builtins.
                "output" => {}
                "execution" => {}
                "program" => {}
                _ => panic!("Unknown memory segment: {name}"),
            }
        }
        res
    }
}
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUN-uI1UJvzpDpVhF9:-OEUN-uI1UJvzpDpVhFA:b-69eeaq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L217)):*
> ```XML
>         assert_eq!(components.mul_opcode_is_small_t_is_imm_t.len(), 0);
>         assert_eq!(components.mul_opcode_is_small_t_is_imm_f.len(), 0);
>         assert_eq!(components.mul_opcode_is_small_f_is_imm_f.len(), 11146);
> ```

why are these changed? are you running with dev mode on?
turn it off



_Code quote:_
```XML
l
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUNBvGESESzKbKalUL:-OEUNBvGESESzKbKalUM:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L300)):*
> ```XML
>         let input = small_cairo_input();
> 
>         // Check opcode components.
> ```





_Suggestion:_
```XML
Test
```
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUNDbZ-lbf0U2OfO1y:-OEUNDbZ-lbf0U2OfO1z:b-sqt4ut) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L359)):*
> ```XML
>         assert_eq!(components.ret_opcode.len(), 462);
> 
>         // Check builtins
> ```

same and point at eol.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 360 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUNKQ4-cKUnQ5ALIrE:-OEUNKQ4-cKUnQ5ALIrF:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L360)):*
> ```XML
> 
>         // Check builtins
>         let builtins = input.builtins_segments;
> ```





_Suggestion:_
```XML
builtins_segments
```
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUM7xUE58uaA705UYR:-OEUM7xUE58uaA705UYS:b-wi5vz4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/plain.rs#L73)):*
> ```XML
>             })
>         });
>     let trace = runner.relocated_trace.clone().unwrap();
> ```

it's a large object
its p [...]

2024-12-19 14:50 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 0 of 4 files reviewed, 11 unresolved discussions (waiting on @DavidLevitGurevich and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUOTHZ4W6Da-ciZ4Hb:-OEUOTHZ4W6Da-ciZ4Hc:bvyb824) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L145)):*
> ```XML
>         res
>     }
> }
> ```

better!



_Suggestion:_
```XML
// TODO(STAV): Understand if the adapter should pass builtins that won't be supported by stwo.
/// This struct holds the builtins used in a Cairo program.
/// Most of them are not implemented yet by Stwo.
#[derive(Debug, Default)]
pub struct BuiltinsSegments {
    pub range_check_bits_128_builtin: Option<MemorySegmentAddresses>,
    pub range_check_bits_96_builtin: Option<MemorySegmentAddresses>,
    pub bitwise_builtin: Option<MemorySegmentAddresses>,
    pub add_mod_builtin: Option<MemorySegmentAddresses>,
    pub ec_op_builtin: Option<MemorySegmentAddresses>,
    pub ecdsa_builtin: Option<MemorySegmentAddresses>,
    pub keccak_builtin: Option<MemorySegmentAddresses>,
    pub mul_mod_builtin: Option<MemorySegmentAddresses>,
    pub pedersen_builtin: Option<MemorySegmentAddresses>,
    pub poseidon_builtin: Option<MemorySegmentAddresses>,
}
impl BuiltinsSegments {
    /// Create a new `BuiltinsSegments` struct from a map of memory MemorySegmentAddressess.
    pub fn from_memory_segments(
        memory_segments: &HashMap<&str, cairo_vm::air_public_input::MemorySegmentAddresses>,
    ) -> Self {
        let mut res = BuiltinsSegments::default();
        for (name, value) in memory_segments.iter() {
            let value = (value.begin_addr, value.stop_ptr).into();
            match *name {
                "range_check" => res.range_check_bits_128_builtin = Some(value),
                "range_check96" => res.range_check_bits_96_builtin = Some(value),
                "bitwise" => res.bitwise_builtin = Some(value),
                "add_mod" => res.add_mod_builtin = Some(value),
                "ec_op" => res.ec_op_builtin = Some(value),
                "ecdsa" => res.ecdsa_builtin = Some(value),
                "keccak" => res.keccak_builtin = Some(value),
                "mul_mod" => res.mul_mod_builtin = Some(value),
                "pedersen" => res.pedersen_builtin = Some(value),
                "poseidon" => res.poseidon_builtin = Some(value),
                // Output, executaion and program segments are not builtins.
                "output" => {}
                "execution" => {}
                "program" => {}
                _ => panic!("Unknown memory segment: {name}"),
            }
        }
        res
    }
}
```


<!-- Sent from Reviewable.io -->

2024-12-19 18:21 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 0 of 5 files reviewed, 10 unresolved discussions (waiting on @DavidLevitGurevich and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUHstd9GzW2PSNKNFD:-OEUxrsH0zQN0mXWfU8v:b-4l4928) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L10)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

struct represents only buildtins, no need to mention that
</blockquote></details>

It is because the name of the component in the air-infra ends with"builtin" and in the future we would like to make sure it sync.(Same for the _opcdoe in CasmStatesByOpcodes)
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUI-wQ85YblwlR6Ifw:-OEV8JnS9htF4j_dAzAl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L22)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

please remove that
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 145 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUOTHZ4W6Da-ciZ4Hb:-OEV8U_L0eP5-I8y_PLM:b52f8x2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L145)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

better!
</blockquote></details>

Much better! Thanks
___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 73 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUM7xUE58uaA705UYR:-OEV8hE-0p8SwShdycZp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/plain.rs#L73)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it's a large object
its possible to reorder the code and avoid this
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUN-uI1UJvzpDpVhF9:-OEV0awM1CaxJl8r4hNp:bw8oamj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L217)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

why are these changed? are you running with dev mode on?
turn it off
</blockquote></details>

I did s(ame as 245)
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUN6gi-EPfTYq4Ukhh:-OEV3bCV5chHbL2JgPfu:b-7wso34) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e9674ad7fa7aa5b1247e42e8e7164a0438a595b6/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L219)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

is this related?
</blockquote></details>

Not relevant anymore
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 359 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUNDbZ-lbf0U2OfO1y:-OEV3p7W9vvBcGU54y-v:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L359)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

same and point at eol.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUG6eR-GuIX2lcih62:-OEV7wgS7y_0bCxh1PlZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L5)):*
> ```XML
> use cairo_vm::air_public_input::MemorySegmentAddresses;
> 
> // TODO(STAV): Understand if the adapter should pass builtins that won't be supported by stwo.
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 300 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUNBvGESESzKbKalUL:-OEV2S4s1SLVsV7lm1tz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L300)):*
> ```XML
>         let input = small_cairo_input();
> 
>         // Check opcode components.
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 360 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUNKQ4-cKUnQ5ALIrE:-OEV46xF4NbyBbZH_gjP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L360)):*
> ```XML
> 
>         // Check builtins
>         let builtins = input.builtins_segments;
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-22 07:24 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEhF87E2kcj4wMZSwn_:-OEhF87E2kcj4wMZSwna:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f14d7bead742ae5a438a49dd8d0d926c37335ef/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L44)):*
> ```XML
>                 "output" => {}
>                 "execution" => {}
>                 "program" => {}
> ```





_Suggestion:_
```XML
                "output" | "execution" | "program" => {}
```


<!-- Sent from Reviewable.io -->

2024-12-22 07:35 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEhHefDE4xev0erTpQZ:-OEhHefDE4xev0erTpQ_:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f14d7bead742ae5a438a49dd8d0d926c37335ef/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L41)):*
> ```XML
>                 "pedersen" => res.pedersen_builtin = Some(value),
>                 "poseidon" => res.poseidon_builtin = Some(value),
>                 // Output, execution and program segments are not builtins.
> ```





_Suggestion:_
```XML

// Not builtins.
```


<!-- Sent from Reviewable.io -->

2024-12-22 07:36 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEhHy4rEcnnbtXG4qq2:-OEhHy4rEcnnbtXG4qq3:bt4srfe) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f14d7bead742ae5a438a49dd8d0d926c37335ef/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L29)):*
> ```XML
>         let mut res = BuiltinsSegments::default();
>         for (name, value) in memory_segments.iter() {
>             let value = (value.begin_addr, value.stop_ptr).into();
> ```

then remove the some from below



_Suggestion:_
```XML
 let value = Some((value.begin_addr, value.stop_ptr).into());
```


<!-- Sent from Reviewable.io -->

2024-12-22 07:39 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs` line 243 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEhIXPCCWBHS0AmAJHD:-OEhIXPD86_UwMO1H2lI:baf6zlm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f14d7bead742ae5a438a49dd8d0d926c37335ef/stwo_cairo_prover/crates/prover/src/input/vm_import/mod.rs#L243)):*
> ```XML
>                 stop_ptr: 1757348
>             })
>         );
> ```

non-blocking



_Suggestion:_
```XML
        assert_eq!(
            builtins_segments.range_check_bits_128_builtin,
            Some((1715768, 1757348).into()),
        );
```


<!-- Sent from Reviewable.io -->

2024-12-22 07:40 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @DavidLevitGurevich and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUHstd9GzW2PSNKNFD:-OEhF26d29UyIVP5VwUi:b-j8wlka) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L10)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

It is because the name of the component in the air-infra ends with"builtin" and in the future we would like to make sure it sync.(Same for the _opcdoe in CasmStatesByOpcodes)
</blockquote></details>

im not sure it should appear there, @DavidLevitGurevich  wdyt?


<!-- Sent from Reviewable.io -->

2024-12-22 10:26 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @DavidLevitGurevich and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEhHy4rEcnnbtXG4qq2:-OEhtko62XQRA-dIBhI0:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f14d7bead742ae5a438a49dd8d0d926c37335ef/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L29)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

then remove the some from below
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 41 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEhHefDE4xev0erTpQZ:-OEhtlwTCLNBQTP9Pnlz:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f14d7bead742ae5a438a49dd8d0d926c37335ef/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L41)):*
> ```XML
>                 "pedersen" => res.pedersen_builtin = Some(value),
>                 "poseidon" => res.poseidon_builtin = Some(value),
>                 // Output, execution and program segments are not builtins.
> ```

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEhF87E2kcj4wMZSwn_:-OEhtnCM27CpIqKqUM_q:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/0f14d7bead742ae5a438a49dd8d0d926c37335ef/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L44)):*
> ```XML
>                 "output" => {}
>                 "execution" => {}
>                 "program" => {}
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-22 11:20 UTC, ohad-starkware requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @DavidLevitGurevich and @Stavbe)

___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEi5C6jElU3fdoRahRH:-OEi5C6jElU3fdoRahRI:b-l6mwxj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7a75311dacc900e87f8e41b25a955465e0d3d213/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L68)):*
> ```XML
>     let args = Args::try_parse_from(args)?;
> 
>     // dev_mode = true
> ```

remove


<!-- Sent from Reviewable.io -->

2024-12-22 13:21 UTC, Stavbe commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/269?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#269** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/269?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/269?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#268** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/268?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-23 07:56 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @DavidLevitGurevich and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/adapted_prover/src/main.rs` line 68 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEi5C6jElU3fdoRahRH:-OEmWBDk4jLl9SqqIcP_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/7a75311dacc900e87f8e41b25a955465e0d3d213/stwo_cairo_prover/crates/adapted_prover/src/main.rs#L68)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-23 08:16 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @DavidLevitGurevich, @ohad-starkware, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 5 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmWzphE7regdvd4hr-:-OEmWzphE7regdvd4hr0:b-wum5ui) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/04a145d36b284cfa4158a7e1a123f7f6809cdc78/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L5)):*
> ```XML
> use cairo_vm::air_public_input::MemorySegmentAddresses;
> 
> // TODO(Stav): Understand if the adapter should pass builtins that won't be supported by stwo.
> ```

I think we can decide on that now and remove the TODO.
Any reason not to support all the builtins in this struct?



_Code quote:_
```XML
// TODO(Stav): Understand if the adapter should pass builtins that won't be supported by stwo.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmXTqH-cPOHnc0dYy4:-OEmXTqIAIMVXkF6voUq:byp18fd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/04a145d36b284cfa4158a7e1a123f7f6809cdc78/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L7)):*
> ```XML
> // TODO(Stav): Understand if the adapter should pass builtins that won't be supported by stwo.
> /// This struct holds the builtins used in a Cairo program.
> /// Most of them are not implemented yet by Stwo.
> ```

Remove



_Code quote:_
```XML
/// Most of them are not implemented yet by Stwo.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmYeeM7MehhDZT1mC7:-OEmYeeM7MehhDZT1mC8:bc7dswa) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/04a145d36b284cfa4158a7e1a123f7f6809cdc78/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L9)):*
> ```XML
> /// Most of them are not implemented yet by Stwo.
> #[derive(Debug, Default)]
> pub struct BuiltinsSegments {
> ```

Does Default here set all the values as None?
I think the code that construct this struct should have a unit test



_Code quote:_
```XML
#[derive(Debug, Default)]
pub struct BuiltinsSegments {
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 24 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmXwfF2MYs6-0Ps7ca:-OEmXwfF2MYs6-0Ps7cb:b-ciaib0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/04a145d36b284cfa4158a7e1a123f7f6809cdc78/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L24)):*
> ```XML
> impl BuiltinsSegments {
>     /// Create a new `BuiltinsSegments` struct from a map of memory MemorySegmentAddressess.
>     pub fn from_memory_segments(
> ```

Consider to implement the From trait, and then you'll be able to just use into()
non-blocking



_Code quote:_
```XML
    pub fn from_memory_segments(
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmXrksD0o2uaTURNV2:-OEmXrksD0o2uaTURNV3:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/04a145d36b284cfa4158a7e1a123f7f6809cdc78/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L25)):*
> ```XML
>     /// Create a new `BuiltinsSegments` struct from a map of memory MemorySegmentAddressess.
>     pub fn from_memory_segments(
>         memory_segments: &HashMap<&str, cairo_vm::air_public_input::MemorySegmentAddresses>,
> ```





_Suggestion:_
```XML
    pub fn from_memory_segments(
        memory_segments: &HashMap<&str, MemorySegmentAddresses>,
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 31 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmZnPj39ChdGHvAzPa:-OEmZnPj39ChdGHvAzPb:bxw4n36) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/04a145d36b284cfa4158a7e1a123f7f6809cdc78/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L31)):*
> ```XML
>             let value = Some((value.begin_addr, value.stop_ptr).into());
>             match *name {
>                 "range_check" => res.range_check_bits_128_builtin = value,
> ```

Consider to use BuitinName enum from cairo_vm instead of hardcoded strings



_Code quote:_
```XML
            match *name {
                "range_check" => res.range_check_bits_128_builtin = value,
```


<!-- Sent from Reviewable.io -->

2024-12-23 10:28 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @DavidLevitGurevich, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 5 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmWzphE7regdvd4hr-:-OEmdlkj5vMLjOC8z3nr:b-rapngv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L5)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I think we can decide on that now and remove the TODO.
Any reason not to support all the builtins in this struct?
</blockquote></details>

If Stwo won't do anything with then why? 
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 7 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmXTqH-cPOHnc0dYy4:-OEn2opj78d5qT3RYpPZ:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L7)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmYeeM7MehhDZT1mC7:-OEmeBeY39I4N6de04jD:b-s1bt18) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L9)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does Default here set all the values as None?
I think the code that construct this struct should have a unit test
</blockquote></details>

Yes, added.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmXrksD0o2uaTURNV2:-OEn2uT2BEm3LyC4fuv_:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L25)):*
> ```XML
>     /// Create a new `BuiltinsSegments` struct from a map of memory MemorySegmentAddressess.
>     pub fn from_memory_segments(
>         memory_segments: &HashMap<&str, cairo_vm::air_public_input::MemorySegmentAddresses>,
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-23 13:14 UTC, shaharsamocha7 requested changes
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @DavidLevitGurevich, @ohad-starkware, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 5 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmWzphE7regdvd4hr-:-OEnbtP29Ca4R1cvFs8W:bgegf9c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L5)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

If Stwo won't do anything with then why?
</blockquote></details>

I don't understand, stwo has to handle all the builtins that are used by the program.
We can't just ignore them.

Another alternative is to assert that the "unsupported" builtins are not in use
but I don't think this is a good place for this.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmXrksD0o2uaTURNV2:-OEncvKJ1ZHYOrql7YRV:b-ac20jb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L25)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm sorry but the previous impl was better because I don't like the 
`let builtins_segments = memory_segments.into();`

Can you revert?
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEnd43q6bbHClkgzMzg:-OEnd43q6bbHClkgzMzh:bjxfxtb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L73)):*
> ```XML
>         assert_eq!(builtins_segments.add_mod_builtin, None);
>         assert_eq!(builtins_segments.ec_op_builtin, None);
>         assert_eq!(builtins_segments.ecdsa_builtin, Some((353, 353).into()));
> ```

Is this a correct behaviour?
I think that if the range is 0 we want to set it as None.
@yuvalsw WDYT?



_Code quote:_
```XML
assert_eq!(builtins_segments.ecdsa_builtin, Some((353, 353).into()));
```
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json` line 425 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEndbgI60CPVLYM7Q9G:-OEndbgI60CPVLYM7Q9H:b-f5ht8o) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json#L425)):*
> ```JSON
>   ],
>   "dynamic_params": null
> }
> ```

Add new line


<!-- Sent from Reviewable.io -->

2024-12-24 09:33 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @DavidLevitGurevich, @ohad-starkware, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEUHstd9GzW2PSNKNFD:-OErwRx-5sPo12ELjU1E:bliuy8t) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/32f7a8c1e561000dd2f1f4336d2b671db29117de/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L10)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

im not sure it should appear there, @DavidLevitGurevich  wdyt?
</blockquote></details>

Since there are builtins here that won’t be implemented by the air-infra, it’s not relevant. Deleted.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 5 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmWzphE7regdvd4hr-:-OEs-gJwDM5hEj72AR_9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L5)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I don't understand, stwo has to handle all the builtins that are used by the program.
We can't just ignore them.

Another alternative is to assert that the "unsupported" builtins are not in use
but I don't think this is a good place for this.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEmXrksD0o2uaTURNV2:-OEs-kzH6Qk1QLyHU2NE:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/a60737c75ea0bb190a2d4f218bb4aaca4582e5c4/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L25)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I'm sorry but the previous impl was better because I don't like the 
`let builtins_segments = memory_segments.into();`

Can you revert?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEnd43q6bbHClkgzMzg:-OErtPba0KhkjxBOsoqN:b-rvc40s) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L73)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is this a correct behaviour?
I think that if the range is 0 we want to set it as None.
@yuvalsw WDYT?
</blockquote></details>

Any idea what the difference is between builtins that don’t get a memory segment and those whose range is 0?
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json` line 425 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEndbgI60CPVLYM7Q9G:-OEs-uFFA-2k7LsEBj0u:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json#L425)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Add new line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 10:25 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEnd43q6bbHClkgzMzg:-OEsBiB9ADOwFlKzoxH6:b6cacm9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L73)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Any idea what the difference is between builtins that don’t get a memory segment and those whose range is 0?
</blockquote></details>

+1 on the question


<!-- Sent from Reviewable.io -->

2024-12-26 08:13 UTC, yuvalsw requested changes
> Reviewed 1 of 4 files at r1, 1 of 2 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: all files reviewed, 13 unresolved discussions (waiting on @Alon-Ti, @DavidLevitGurevich, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEnd43q6bbHClkgzMzg:-OF0tF9uE5a6HflYDwqs:b-cf6hns) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L73)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

+1 on the question
</blockquote></details>

@shaharsamocha7 - I think you are right. Both would probably work, but we do want to be as consistent as possible. Similar inconsistencies made us some trouble before.
@Stavbe - I think it may be a question of whether the builtin appears in the program but is unused (empty range) or simply does not appear in the program (no memory segment). @Alon-Ti or Yair Vaknin may know to confirm/correct.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0oigQ-_jpa-OIHjjG:-OF0oigQ-_jpa-OIHjjH:bkn1udb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L9)):*
> ```XML
> #[derive(Debug, Default)]
> pub struct BuiltinsSegments {
>     pub range_check_bits_128: Option<MemorySegmentAddresses>,
> ```

is this list ordered in some way? I'd expect it to either be alphabetical or some logical sense (I think there is a constant order of the builtins), in which case I'd expect e.g. add_mod and mul_mod to be next to each other.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0pMhn6sdNI_Y9pEl9:-OF0pMhn6sdNI_Y9pElA:b862rzb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L22)):*
> ```XML
> 
> impl BuiltinsSegments {
>     /// Create a new `BuiltinsSegments` struct from a map of memory MemorySegmentAddressess.
> ```

builtin_name -> MemorySegmentAddressess ?



_Code quote:_
```XML
map of memory MemorySegmentAddressess.
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0qcBK7t9yG7nTyjqd:-OF0qcBL-REGAwiR1d9J:b-nh6ds4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L26)):*
> ```XML
>         let mut res = BuiltinsSegments::default();
>         for (name, value) in memory_segments.iter() {
>             let value = Some((value.begin_addr, value.stop_ptr).into());
> ```

It looks like you are converting from a MemorySegmentAddresses to a tuple and back, am I missing something?
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0rQFj1XDY0URWgvnz:-OF0rQFj1XDY0URWgvo-:b-r2yhvb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L59)):*
> ```XML
>     fn test_builtins_segments() {
>         let mut d = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
>         d.push("src/input/test_builtins_segments/air_pub.json");
> ```

I see this is used in other places too, but:
1. I don't like the name `d`.  `dir`?
2. This seems to need to be a util function. Can you please move it (in a separate PR - either before merging this one, or after, but with adding a TODO here).



_Code quote:_
```XML
        let mut d = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        d.push("src/input/test_builtins_segments/air_pub.json");
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0vQdR3dbIZsxdx08Q:-OF0vQdR3dbIZsxdx08R:bs1sknm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L59)):*
> ```XML
>     fn test_builtins_segments() {
>         let mut d = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
>         d.push("src/input/test_builtins_segments/air_pub.json");
> ```

Seems like this input doesn't use any builtin (all builtin segments are empty) - do we have a better input for this test which belongs to a program that did use builtins?
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 61 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0s4lb0jHaJLVW8fM_:-OF0s4lb0jHaJLVW8fMa:b-jvyjt7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L61)):*
> ```XML
>         d.push("src/input/test_builtins_segments/air_pub.json");
>         let pub_data_string = std::fs::read_to_string(&d)
>             .unwrap_or_else(|_| panic!("Unable to read file: {}", d.display()));
> ```

is the `.display()` needed?



_Code quote:_
```XML
d.display())
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 64 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0sLcm38LgA6wkPWMq:-OF0sLcm38LgA6wkPWMr:b2ni8l0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L64)):*
> ```XML
>         let pub_data: PublicInput<'_> =
>             sonic_rs::from_str(&pub_data_string).expect("Unable to parse JSON");
>         let builtins_segments = BuiltinsSegments::from_memory_segments(&pub_data.memory_segments);
> ```

nit



_Suggestion:_
```XML
let builtin_segments = BuiltinSegments::from_mem
```
___
*[`stwo_cairo_prover/crates/prover/src/input/mod.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0vtlF3lSmQ9tYS8eH:-OF0vnqH22_Fu48PHWnC:bh3skgy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/mod.rs#L22)):*
> ```XML
>     pub public_mem_addresses: Vec<u32>,
> 
>     // Builtins.
> ```

I think this comment can be removed.



_Code quote:_
```XML
    // Builtins
```
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json` line 0 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0x7PI07M0WbLjyiV2:-OF0x7PJAMY4JcEII9aZ:b-58q4tl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json#L0)):*
Can you somehow doc how this was generated, what program it relates to, etc.?


<!-- Sent from Reviewable.io -->

2024-12-26 12:48 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEnd43q6bbHClkgzMzg:-OF2-KHI8VDIAl3o2OlQ:bjr6lr1) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L73)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

@shaharsamocha7 - I think you are right. Both would probably work, but we do want to be as consistent as possible. Similar inconsistencies made us some trouble before.
@Stavbe - I think it may be a question of whether the builtin appears in the program but is unused (empty range) or simply does not appear in the program (no memory segment). @Alon-Ti or Yair Vaknin may know to confirm/correct.
</blockquote></details>

if a builtin is declared but never used (control flow) it gets 0 range
we need to convert that to None in the code above


<!-- Sent from Reviewable.io -->

2024-12-26 14:25 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @Alon-Ti, @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 73 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OEnd43q6bbHClkgzMzg:-OF2IZVj9ZwY9SwVyDhT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/cf088896107f7b20c3436bfaa6755e0e148fa765/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L73)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

if a builtin is declared but never used (control flow) it gets 0 range
we need to convert that to None in the code above
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0oigQ-_jpa-OIHjjG:-OF1ebmO4szw7P5d5ZeM:b-ou6kf4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L9)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is this list ordered in some way? I'd expect it to either be alphabetical or some logical sense (I think there is a constant order of the builtins), in which case I'd expect e.g. add_mod and mul_mod to be next to each other.
</blockquote></details>

reordered according to the BuiltiName enum
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 22 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0pMhn6sdNI_Y9pEl9:-OF2IJGH4cRvWSwsjahl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L22)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

builtin_name -> MemorySegmentAddressess ?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0qcBK7t9yG7nTyjqd:-OF1fBeg726YhDFguryS:bu3d12x) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L26)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

It looks like you are converting from a MemorySegmentAddresses to a tuple and back, am I missing something?
</blockquote></details>

It’s either that or sending the hashmap by value. Since there’s a problem with borrowing and no `Clone` implementation exists for `MemorySegmentAddresses`.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0rQFj1XDY0URWgvnz:-OF1tb852hhvfxoLHPrD:bb74ce2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L59)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I see this is used in other places too, but:
1. I don't like the name `d`.  `dir`?
2. This seems to need to be a util function. Can you please move it (in a separate PR - either before merging this one, or after, but with adding a TODO here).
</blockquote></details>

Sure
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0vQdR3dbIZsxdx08Q:-OF2IcPV9QU5qV1J3EdP:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L59)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Seems like this input doesn't use any builtin (all builtin segments are empty) - do we have a better input for this test which belongs to a program that did use builtins?
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 61 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0s4lb0jHaJLVW8fM_:-OF1u67nBBLr0-Nh-10c:b-9f3gvd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L61)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

is the `.display()` needed?
</blockquote></details>

"std::path::PathBuf` cannot be formatted with the default formatter; call `.display()` on it"
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json` line  at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0x7PI07M0WbLjyiV2:-OF2IcyGEJnarkwjHDwC:b-vntc5v) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/air_pub.json#L)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Can you somehow doc how this was generated, what program it relates to, etc.?
</blockquote></details>

Added in the json


<!-- Sent from Reviewable.io -->

2024-12-26 17:11 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-:-OF2wqgw5zXorZdwlY99:bnfp4nl)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @Alon-Ti, @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)



<!-- Sent from Reviewable.io -->

2024-12-29 07:08 UTC, shaharsamocha7 requested changes
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: all files reviewed, 13 unresolved discussions (waiting on @DavidLevitGurevich, @Stavbe, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json` line 1 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGDrs58lqNOxLXKM_z:-OFGDrs58lqNOxLXKMa-:b-iefn4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json#L1)):*
> ```JSON
> {
> ```

Is there anything special about this program, or is it just an arbitrary test input?
Consider to rename the file to `test_public_input.json`
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json` line 2 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGE0-35XL9NTml5PQL:-OFGE0-35XL9NTml5PQM:btxde6z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json#L2)):*
> ```JSON
> {
>   "_comment": "This file contains the AIR public input of the `blake2s_felts` Cairo program from `cairo-vm/cairo_programs`. It was generated by compiling this program in proof mode and running the VM with a specified path to output the AIR public inputs.",
> ```

Note that this comment was added manually, meaning if one will regenerate this input file, the comment will be gone.



_Code quote:_
```JSON
{
  "_comment": "This file contains the AIR public input of the `blake2s_felts` Cairo program from `cairo-vm/cairo_programs`. It was generated by compiling this program in proof mode and running the VM with a specified path to output the AIR public inputs.",
```
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json` line 3036 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGEFds39n_fITpCjXR:-OFGEFds39n_fITpCjXS:b-hvbrl4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json#L3036)):*
> ```JSON
>   ],
>   "dynamic_params": null
> }
> ```

add new line
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGCIacBfkwlWXgOVN4:-OFGCIacBfkwlWXgOVN5:b-44ytu9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L18)):*
> ```XML
>     pub range_check_bits_96: Option<MemorySegmentAddresses>,
>     pub add_mod: Option<MemorySegmentAddresses>,
>     pub mul_mod: Option<MemorySegmentAddresses>,
> ```

Reorder alphabetically



_Code quote:_
```XML
    pub range_check_bits_128: Option<MemorySegmentAddresses>,
    pub pedersen: Option<MemorySegmentAddresses>,
    pub ecdsa: Option<MemorySegmentAddresses>,
    pub keccak: Option<MemorySegmentAddresses>,
    pub bitwise: Option<MemorySegmentAddresses>,
    pub ec_op: Option<MemorySegmentAddresses>,
    pub poseidon: Option<MemorySegmentAddresses>,
    pub range_check_bits_96: Option<MemorySegmentAddresses>,
    pub add_mod: Option<MemorySegmentAddresses>,
    pub mul_mod: Option<MemorySegmentAddresses>,
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 31 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGCOEO28vE4S_NFqgl:-OFGCOEO28vE4S_NFqgm:bwareko) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L31)):*
> ```XML
>                 } else {
>                     Some((value.begin_addr, value.stop_ptr).into())
>                 };
> ```

comment that it filters empty ranged builtins
Also, consider to assert that value.begin_addr <= value.stop_ptr and move to a get_segment function



_Code quote:_
```XML
                let segments = if value.begin_addr == value.stop_ptr {
                    None
                } else {
                    Some((value.begin_addr, value.stop_ptr).into())
                };
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGD5yn9xrI4MHVbUnR:-OFGD5yo2v2ko-fsAVKS:bvix5kp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L68)):*
> ```XML
>             .unwrap_or_else(|_| panic!("Unable to read file: {}", path.display()));
>         let pub_data: PublicInput<'_> =
>             sonic_rs::from_str(&pub_data_string).expect("Unable to parse JSON");
> ```

this should be moved to a test function. Is it your TODO?



_Code quote:_
```XML
        let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        path.push("src/input/test_builtins_segments/blake2s_felts_public_input.json");
        let pub_data_string = std::fs::read_to_string(&path)
            .unwrap_or_else(|_| panic!("Unable to read file: {}", path.display()));
        let pub_data: PublicInput<'_> =
            sonic_rs::from_str(&pub_data_string).expect("Unable to parse JSON");
```


<!-- Sent from Reviewable.io -->

2024-12-29 13:15 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 3 of 8 files reviewed, 12 unresolved discussions (waiting on @DavidLevitGurevich, @shaharsamocha7, and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGCIacBfkwlWXgOVN4:-OFGpLmlEuc5ebgYm7eT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L18)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Reorder alphabetically
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 31 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGCOEO28vE4S_NFqgl:-OFGpNQW-5i6o2O8ywBM:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L31)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

comment that it filters empty ranged builtins
Also, consider to assert that value.begin_addr <= value.stop_ptr and move to a get_segment function
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGD5yn9xrI4MHVbUnR:-OFGlvsuAN_tnQVrlk3k:b2nign6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L68)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

this should be moved to a test function. Is it your TODO?
</blockquote></details>

yes
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json` line 1 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGDrs58lqNOxLXKM_z:-OFGm7Pm9fkIKOMu4GCc:b-1b49m5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json#L1)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Is there anything special about this program, or is it just an arbitrary test input?
Consider to rename the file to `test_public_input.json`
</blockquote></details>

Arbitrary 
___
*[`stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json` line 3036 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGEFds39n_fITpCjXR:-OFGpSKL88TkwDyM-oW6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/test_builtins_segments/blake2s_felts_public_input.json#L3036)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

add new line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-30 05:54 UTC, yuvalsw requested changes
> Reviewed 2 of 7 files at r7, 1 of 3 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: all files reviewed, 10 unresolved discussions (waiting on @DavidLevitGurevich, @shaharsamocha7, and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGCIacBfkwlWXgOVN4:-OFL2gRMAxsjnc8tFMPe:badrq5p) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L18)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think I'd keep an order similar to the order in BuiltinName, WDYT?
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGD5yn9xrI4MHVbUnR:-OFL5w-m3lEbI3s3t94G:b-ofdx7i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L68)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

I can’t move it out of this function due to a borrowing issue with `pub_data_string`:  
"returns a value referencing data owned by the current function."
</blockquote></details>

Not sure what the exact issue is (need to see), but you can clone if doesn't work otherwise.
(Again - TODO here is completely fine, then resolve this issue separately)
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 26 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0qcBK7t9yG7nTyjqd:-OFL5VYg7RC5v2x36Km6:b-1j3f2i) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L26)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

It’s either that or sending the hashmap by value. Since there’s a problem with borrowing and no `Clone` implementation exists for `MemorySegmentAddresses`.
</blockquote></details>

Oh... Another PR to LC :) It should definitely have clone.
Resolving for now.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs` line 59 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OF0rQFj1XDY0URWgvnz:-OFL6Jaf6mhyGT4WIKRg:b5frojp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9b82aedeb32185a861a8af447af870c5603e1c87/stwo_cairo_prover/crates/prover/src/input/builtins_segments.rs#L59)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

Sure
</blockquote></details>

2. Continuing on Shahar's comment. Resolving this one.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 54 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFL3Uu71LDhOQIzgYmz:-OFL3Uu891Hmm2rwLNgq:b-572nsm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b4ba6e1b650266a59f1e2e252c44607e31e0bb16/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L54)):*
> ```XML
>                     assert!(
>                         value.begin_addr < value.stop_ptr,
>                         "Invalid segment addresses for builtin: {}",
> ```

1. Add the faulty addresses.
2. Is panic what we want in this case?
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 56 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFL3m3QCEdlrYlajmyW:-OFL3m3QCEdlrYlajmyX:b-3qnc53) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b4ba6e1b650266a59f1e2e252c44607e31e0bb16/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L56)):*
> ```XML
>                         "Invalid segment addresses for builtin: {}",
>                         name
>                     );
> ```

suggestion



_Suggestion:_
```XML
                    assert!(
                        value.begin_addr < value.stop_ptr,
                        "Invalid segment addresses for builtin '{name}'"
                    );
```
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 83 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFL6aCm2Ux30OwHhyyJ:-OFL6aCm2Ux30OwHhyyK:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b4ba6e1b650266a59f1e2e252c44607e31e0bb16/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L83)):*
> ```XML
>             sonic_rs::from_str(&pub_data_string).expect("Unable to parse JSON");
> 
>         let builtins_segments = BuiltinSegments::from_memory_segments(&pub_data.memory_segments);
> ```





_Suggestion:_
```XML
builtin_segments = BuiltinSegments::from_mem
```


<!-- Sent from Reviewable.io -->

2024-12-30 07:20 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-:-OFLQvJS1v6_8SQptji-:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @DavidLevitGurevich and @Stavbe)



<!-- Sent from Reviewable.io -->

2024-12-30 09:24 UTC, Stavbe reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @DavidLevitGurevich and @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 18 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGCIacBfkwlWXgOVN4:-OFLeVb3CtPr_OjQSGKM:b-psemjv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L18)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

I think I'd keep an order similar to the order in BuiltinName, WDYT?
</blockquote></details>

It looks very random, and it’s different from the order in `AirPrivateInputSerializable`, so maybe alphabetical order is the right compromise.
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 68 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFGD5yn9xrI4MHVbUnR:-OFLfciB4UE1PxyU7jXt:b-ot7smo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c4f0e6722671442cb2427cdb9b02b4868adb30e5/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L68)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

Not sure what the exact issue is (need to see), but you can clone if doesn't work otherwise.
(Again - TODO here is completely fine, then resolve this issue separately)
</blockquote></details>

Clone doesn't solve the issue.
Can add a todo anyway
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 54 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFL3Uu71LDhOQIzgYmz:-OFLr1vJ2-FoHF---vIM:b-c410uz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b4ba6e1b650266a59f1e2e252c44607e31e0bb16/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L54)):*
<details><summary><i>Previously, yuvalsw wrote…</i></summary><blockquote>

1. Add the faulty addresses.
2. Is panic what we want in this case?
</blockquote></details>

1. Done
2. Other suggestions? It shouldn't be a valid output of the vm.


<!-- Sent from Reviewable.io -->

2024-12-30 15:35 UTC, yuvalsw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-:-OFNCETtCnDya3xcqaYo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @DavidLevitGurevich and @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 54 at r10](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFL3Uu71LDhOQIzgYmz:-OFNC4YI-i5lT0SVMY6q:b-8f68c3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/b4ba6e1b650266a59f1e2e252c44607e31e0bb16/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L54)):*
<details><summary><i>Previously, Stavbe wrote…</i></summary><blockquote>

1. Done
2. Other suggestions? It shouldn't be a valid output of the vm.
</blockquote></details>

2. It's probably fine
___
*[`stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs` line 67 at r12](https://reviewable.io/reviews/starkware-libs/stwo-cairo/269#-OFNBpuN5F7ledrH0tut:-OFNBpuN5F7ledrH0tuu:bj3bmsj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c7390bd0c3638070a49907f5674fea16619358e8/stwo_cairo_prover/crates/prover/src/input/builtin_segments.rs#L67)):*
> ```XML
> }
> 
> // TODO(Stav): move read json to a test function.
> ```

better move right above the test function itself.


<!-- Sent from Reviewable.io -->

2024-12-31 09:31 UTC, merged