Implement ColMults in memory_id_to_big
starkware-libs/stwo-cairo pull request #271
Opened 2024-12-22 09:55 UTC by Gali-StarkWare

2024-12-22 09:55 UTC, Gali-StarkWare commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/271?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#271** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/271?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/271?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#270** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/270?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-22 11:19 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi4Egr2Pb8l17V-Kna:-OEi4Egr2Pb8l17V-Knb:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
> ```XML
> /// An aligned vector of `u32` that is used to store the multiplicities of the columns, for a direct
> /// transmuting to Vec<PackedM31>.
> pub struct ColMults(Vec<u32>);
> ```





_Suggestion:_
```XML
pub struct MultiplicitiColum {
    data: Vec<u32>
};
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi4RE_2w7UTvHPAvJT:-OEi4RE_2w7UTvHPAvJU:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/mod.rs#L59)):*
> ```XML
> 
> impl ColMults {
>     /// Creates a new `ColMults` with the given size. The elements are initialized to 0.
> ```





_Suggestion:_
```XML
pub struct ColMults(Vec<u32>);
impl ColMults {
    /// Creates a new `ColMults` with the given size. The elements are initialized to 0.
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi48_xDHaP3rRJeG5X:-OEi48_xDHaP3rRJeG5Y:bjbevr2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L212)):*
> ```XML
>     }
> 
>     // Assumes mults is aligned and has a length that is a multiple of N_LANES, therefore can be
> ```

this code should be hidden behind the impl of ColMults
there shouldn't be any unsafe code outside the struct,
and the user should be oblivious to the inner structure


<!-- Sent from Reviewable.io -->

2024-12-22 12:04 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 212 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi48_xDHaP3rRJeG5X:-OEiDx-546y4GjOFWY0y:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L212)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this code should be hidden behind the impl of ColMults
there shouldn't be any unsafe code outside the struct,
and the user should be oblivious to the inner structure
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi4Egr2Pb8l17V-Kna:-OEi8XgY-q4MdNM_ArIm:b-apfmuy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
> ```XML
> /// An aligned vector of `u32` that is used to store the multiplicities of the columns, for a direct
> /// transmuting to Vec<PackedM31>.
> pub struct ColMults(Vec<u32>);
> ```

Done. Why not have a tuple struct if there is only 1 item in it? Because .data is better than .0?
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi4RE_2w7UTvHPAvJT:-OEi8XTn3DqS3ANc7w7a:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/mod.rs#L59)):*
> ```XML
> 
> impl ColMults {
>     /// Creates a new `ColMults` with the given size. The elements are initialized to 0.
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-22 13:17 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi4Egr2Pb8l17V-Kna:-OEiU40o38gW_v_l9gGV:bk1fdp6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done. Why not have a tuple struct if there is only 1 item in it? Because .data is better than .0?
</blockquote></details>

IMO tuple struct is benficial only when the inner representation is trivial.
if you find yourself pondering on what some_struct.0 is, then the field should deserves a name.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiUpSV-_xUNsiQY-OR:-OEiUpSV-_xUNsiQY-OS:b-pre7hm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L78)):*
> ```XML
> 
>     /// Transmutes the internal data to a Vec<PackedM31>.
>     /// The size of the internal data must be a multiple of N_LANES.
> ```

you can assert than uppon creation, 
perhaps take 'log_size' instead of size in new(), and assert that it is geq 4
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiUmLq9vVNsvJLAWkf:-OEiUmLq9vVNsvJLAWkg:b-lz62r2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L79)):*
> ```XML
>     /// Transmutes the internal data to a Vec<PackedM31>.
>     /// The size of the internal data must be a multiple of N_LANES.
>     /// The internal data is forgotten.
> ```

implementation detail, remove
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiV1NV-fR4bBVjTSVu:-OEiV1NV-fR4bBVjTSVv:b2b78n4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L80)):*
> ```XML
>     /// The size of the internal data must be a multiple of N_LANES.
>     /// The internal data is forgotten.
>     pub fn as_packed_m31(self) -> Vec<PackedM31> {
> ```

cool funcion, but I hate that name
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVOcO0ntBkLklTmbM:-OEiVOcO0ntBkLklTmbN:b-t7mm7q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L103)):*
> ```XML
>     #[test]
>     fn test_multiplicities_column_new() {
>         let col_mults = super::MultiplicityColumn::new(N_LANES);
> ```

rename, and larger size
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVTQy6yyAFYYnLSI0:-OEiVTQy6yyAFYYnLSI1:bb7lbs2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L105)):*
> ```XML
>         let col_mults = super::MultiplicityColumn::new(N_LANES);
> 
>         assert!(col_mults.data.len() == N_LANES);
> ```

nice
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVVTm2NL1fFLdQOHd:-OEiVVTm2NL1fFLdQOHe:b-hsywbj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L106)):*
> ```XML
> 
>         assert!(col_mults.data.len() == N_LANES);
>         assert!(col_mults.data.iter().sum::<u32>() == 0);
> ```

sum is weird hrere, use 'all'
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVah-7_JDoXWNqrRN:-OEiVah-7_JDoXWNqrRO:b-fitm2u) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L107)):*
> ```XML
>         assert!(col_mults.data.len() == N_LANES);
>         assert!(col_mults.data.iter().sum::<u32>() == 0);
>         assert!(col_mults.data.as_ptr() as usize % std::mem::size_of::<super::PackedM31>() == 0);
> ```

document the purpose of this assert
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVfHt-VzVBv5UQlR4:-OEiVfHt-VzVBv5UQlR5:bb7od0r) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L112)):*
> ```XML
>     #[test]
>     fn test_multiplicities_column_as_packed_m31() {
>         let col_mults = super::MultiplicityColumn::new(N_LANES);
> ```

same
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVkBnAA9vDeHcCkQG:-OEiVkBnAA9vDeHcCkQH:blbjz6j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L116)):*
> ```XML
> 
>         assert!(packed_vec.len() == 1);
>         assert!(packed_vec[0].to_array().iter().all(|&x| x == M31::zero()));
> ```

can we have a noisy test instead?
use SmallRng for seeded randomness


<!-- Sent from Reviewable.io -->

2024-12-22 15:05 UTC, shaharsamocha7 requested changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 1 of 4 files reviewed, 15 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEir3UPDc91RVK5RJIN:-OEir3UQ26JGDhwWhhqM:b-emgfxw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L53)):*
> ```XML
> }
> 
> // TODO(Gali): Move to somewhere else.
> ```

Are you going to do this soon? I don't like that this code is in the mod file



_Code quote:_
```XML
// TODO(Gali): Move to somewhere else.
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEirJNc0YPvhucryMEi:-OEirJNc0YPvhucryMEj:b-yhilcd) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L55)):*
> ```XML
> // TODO(Gali): Move to somewhere else.
> /// An aligned vector of `u32` that is used to store the multiplicities of the columns, for a direct
> /// transmuting to Vec<PackedM31>.
> ```

transmuting to Vec<PackedM31> is an implementation detail



_Suggestion:_
```XML
// TODO(Gali): Move to somewhere else.
/// An aligned vector of `u32` that is used to store the multiplicities of the columns for logup arguments.
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEir_Vb4oxYsZNadOWh:-OEir_Vb4oxYsZNadOWi:b61slnu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L74)):*
> ```XML
>         Self {
>             data: unsafe { Vec::from_raw_parts(vec_ptr, size, size) },
>         }
> ```

I think this code is a bit complex.
Consider to create a column of zeros and then transmute it to Vec<M31>



_Code quote:_
```XML
        let layout = alloc::Layout::from_size_align(
            size * std::mem::size_of::<u32>(),
            std::mem::size_of::<PackedM31>(),
        )
        .unwrap();
        let vec_ptr = unsafe { alloc::alloc(layout) as *mut u32 };

        unsafe {
            ptr::write_bytes(vec_ptr, 0, size);
        }
        Self {
            data: unsafe { Vec::from_raw_parts(vec_ptr, size, size) },
        }
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEisA3109QhzmM4Q_05:-OEisA3109QhzmM4Q_06:b9zndit) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L81)):*
> ```XML
>     /// The internal data is forgotten.
>     pub fn as_packed_m31(self) -> Vec<PackedM31> {
>         assert!(self.data.len() % N_LANES == 0);
> ```

Move this assert to the new function (we don't want to check it each time)



_Code quote:_
```XML
        assert!(self.data.len() % N_LANES == 0);
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEitO0dCnfk8dxtlwZJ:-OEitO0dCnfk8dxtlwZK:b-gqjcv3) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L90)):*
> ```XML
>             )
>         };
>         std::mem::forget(self.data);
> ```

Can you use cast from bytemuck instead?



_Code quote:_
```XML
        let packed_vec = unsafe {
            Vec::from_raw_parts(
                self.data.as_ptr() as *mut PackedM31,
                self.data.len() / N_LANES,
                self.data.capacity() / N_LANES,
            )
        };
        std::mem::forget(self.data);
```


<!-- Sent from Reviewable.io -->

2024-12-23 10:08 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 1 of 4 files reviewed, 15 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEi4Egr2Pb8l17V-Kna:-OEib6NvC6CqIua1UbUf:btn461w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c5d44558015701681e97373e4a6e59a88981712d/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

IMO tuple struct is benficial only when the inner representation is trivial.
if you find yourself pondering on what some_struct.0 is, then the field should deserves a name.
</blockquote></details>

Got it
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEir3UPDc91RVK5RJIN:-OEmqV4e-EAbUcGymbkp:b87b3s6) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Are you going to do this soon? I don't like that this code is in the mod file
</blockquote></details>

I'm not sure what would be the right place for it. I thought about moving it to the mod file in memory, but it's not ideal since it's also should be used in range_check_vector. What do you think about having a utils file in components?
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEirJNc0YPvhucryMEi:-OEmNim102_ZpX6RPjtb:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L55)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

transmuting to Vec<PackedM31> is an implementation detail
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 78 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiUpSV-_xUNsiQY-OR:-OEmdpn247BLVEdM459z:bjln28d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L78)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you can assert than uppon creation, 
perhaps take 'log_size' instead of size in new(), and assert that it is geq 4
</blockquote></details>

Moved the assertion, but kept the size because we agreed that log_size might be an overkill, as we only need to pad to the next multiple of 16
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiUmLq9vVNsvJLAWkf:-OEmNralArfKvGpkEO6j:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L79)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

implementation detail, remove
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 80 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiV1NV-fR4bBVjTSVu:-OEmSF-wDLdpUE_V1YIP:b-yn63tu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L80)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

cool funcion, but I hate that name
</blockquote></details>

See if it's better now
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEisA3109QhzmM4Q_05:-OEmRyxI5tJMBtRmwwn4:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L81)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Move this assert to the new function (we don't want to check it each time)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 103 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVOcO0ntBkLklTmbM:-OEmdmJE0bUOua9P6vn9:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L103)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

rename, and larger size
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 105 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVTQy6yyAFYYnLSI0:-OEmO3R86-p--o5LR1Kz:b32vhw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L105)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

nice
</blockquote></details>

:)
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 106 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVVTm2NL1fFLdQOHd:-OEm_iJl5MQSnfdbzqIW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L106)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

sum is weird hrere, use 'all'
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVah-7_JDoXWNqrRN:-OEmchzf8EpbS4HfGd_B:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L107)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

document the purpose of this assert
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 112 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVfHt-VzVBv5UQlR4:-OEmdkcC3552tPhCia78:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L112)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEiVkBnAA9vDeHcCkQG:-OEmjA6v97BMjxH1C37M:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L116)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

can we have a noisy test instead?
use SmallRng for seeded randomness
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-23 15:47 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoBuoN4HWOkiqUFXXm:-OEoBuoN4HWOkiqUFXXn:b-lum097) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L216)):*
> ```XML
>         length: mults_vec.len() * N_LANES,
>         data: mults_vec,
>     };
> ```

to avoid deciding on variable names



_Suggestion:_
```XML

    let multiplicities = BaseColumn {
        length: mults_vec.len() * N_LANES,
        data: mults.into_vec(),
    };
```


<!-- Sent from Reviewable.io -->

2024-12-23 15:50 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCdZD7sDcJqPAly8r:-OEoCdZD7sDcJqPAly8s:b3kre) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L39)):*
> ```XML
> 
>         let next_multiple_of_16 = ids.len().next_multiple_of(16);
>         let multiplicities = MultiplicityColumn::new(next_multiple_of_16);
> ```

?



_Suggestion:_
```XML

        let multiplicities = MultiplicityColumn::new(ids.len());
```


<!-- Sent from Reviewable.io -->

2024-12-23 15:52 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEitO0dCnfk8dxtlwZJ:-OEoD0Et8EkcQNMGbwUv:b2gvt5n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L90)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Can you use cast from bytemuck instead?
</blockquote></details>

bytemuck wants 32x16 to implement  their traits, which it doesn't


<!-- Sent from Reviewable.io -->

2024-12-23 16:03 UTC, shaharsamocha7 requested changes
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEir3UPDc91RVK5RJIN:-OEoCS0L4fMaONonbj8e:b-81vq97) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L53)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

I'm not sure what would be the right place for it. I thought about moving it to the mod file in memory, but it's not ideal since it's also should be used in range_check_vector. What do you think about having a utils file in components?
</blockquote></details>

yes, can you add a pr that only moves this code later in this stack?
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoEsBB-c7CgL8I3Y43:-OEoEsBC3nRWPc0ikKKM:b-15ltr0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L94)):*
> ```XML
>             .array_chunks::<N_LANES>()
>             .map(|&chunk| unsafe { PackedM31::from_simd_unchecked(Simd::from_array(chunk)) });
>         let multiplicities_it = self.multiplicities.into_vec();
> ```

Does it stands for iterator? can you rename it (it is not an iterator)



_Code quote:_
```XML
let multiplicities_it = self.multiplicities.into_vec();
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCmu7E4_CyD_flU1U:-OEoCmu7E4_CyD_flU1V:b-fuqhhx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L63)):*
> ```XML
>     /// Creates a new `MultiplicityColumn` with the given size. The elements are initialized to 0.
>     pub fn new(size: usize) -> Self {
>         let vec_size = size.next_multiple_of(N_LANES) / N_LANES;
> ```

Isn't it div_ceil?



_Code quote:_
```XML
size.next_multiple_of(N_LANES) / N_LANES
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoDahJ2o0GrVMsKiCF:-OEoDahJ2o0GrVMsKiCG:b-d43thi) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L74)):*
> ```XML
> 
>     /// Returns the internal data as a Vec<PackedM31>.
>     pub fn into_vec(self) -> Vec<PackedM31> {
> ```

Consider to rename (non-blocking)
Do we also want `into_cpu_vec() -> Vec<M31>`? 
@ohad-starkware 



_Suggestion:_
```XML
pub fn into_simd_vec(self) -> Vec<PackedM31> {
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoFGI78DP__7yFMAvR:-OEoFGI78DP__7yFMAvS:b74bkur) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L93)):*
> ```XML
>         let mut multiplicity_column = super::MultiplicityColumn::new(6 * N_LANES - 2);
>         let mut vec = vec![M31::zero(); 6 * N_LANES];
>         let mut rng = SmallRng::seed_from_u64(0u64);
> ```

Rename and rearrange



_Suggestion:_
```XML
        let mut rng = SmallRng::seed_from_u64(0u64);
        let mut multiplicity_column = super::MultiplicityColumn::new(6 * N_LANES - 2);
        let mut expected = vec![M31::zero(); 6 * N_LANES];
```
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoECVU-Yl22go8mPMq:-OEoECVU-Yl22go8mPMr:b9qmmm8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L113)):*
> ```XML
>         {
>             assert!(packed_chunk.to_array() == vec_chunk);
>         }
> ```

Why this test access mult_col.data directly?
I think it should assert the result of into_cpu instead of the internals of this struct



_Code quote:_
```XML
        assert!(multiplicity_column.data.len() == 6);
        // The vector should be aligned to the size of PackedM31.
        assert!(
            multiplicity_column.data.as_ptr() as usize % std::mem::size_of::<super::PackedM31>()
                == 0
        );
        for (packed_chunk, vec_chunk) in multiplicity_column
            .into_vec()
            .iter()
            .zip(vec.chunks(N_LANES))
        {
            assert!(packed_chunk.to_array() == vec_chunk);
        }
```


<!-- Sent from Reviewable.io -->

2024-12-24 08:00 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoDahJ2o0GrVMsKiCF:-OErfh7vEM3sHZ61G3HX:b-g9g5qm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to rename (non-blocking)
Do we also want `into_cpu_vec() -> Vec<M31>`? 
@ohad-starkware
</blockquote></details>

im fine with that


<!-- Sent from Reviewable.io -->

2024-12-24 08:38 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEir3UPDc91RVK5RJIN:-OEro0mL4oGESikzhqlW:b-o5qyxx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L53)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

yes, can you add a pr that only moves this code later in this stack?
</blockquote></details>

imo this probably should sit in stwo-air-utils, which doesn't really exist yet
maybe specify that it is supposed to be there?


<!-- Sent from Reviewable.io -->

2024-12-24 08:58 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @Gali-StarkWare, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEir3UPDc91RVK5RJIN:-OErmZgw7m_F6nvIIHyA:bb74ce2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/f37fa5050d84aa9412542cfaec523a555d0ac78e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L53)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

imo this probably should sit in stwo-air-utils, which doesn't really exist yet
maybe specify that it is supposed to be there?
</blockquote></details>

Sure
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCmu7E4_CyD_flU1U:-OErmUSEB4n3FLKTxcpY:bo0pas5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L63)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Isn't it div_ceil?
</blockquote></details>

It is :)
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoDahJ2o0GrVMsKiCF:-OErq2gj8rWgIlgttQyy:b2k6mi9) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L74)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

im fine with that
</blockquote></details>

Is it a yes or a no? :)
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoFGI78DP__7yFMAvR:-OErqjV26BH9nde5fI0_:b-ek6k46) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L93)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Rename and rearrange
</blockquote></details>

Done. Is there a special reason rng should be the first variable to be declared?
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 113 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoECVU-Yl22go8mPMq:-OErr-6K3tR6FQQHZTJr:brg7bjk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L113)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Why this test access mult_col.data directly?
I think it should assert the result of into_cpu instead of the internals of this struct
</blockquote></details>

I wanted to make sure that I indeed create the vector with the proper alignment (before I wrote the into_vec function), but I guess it's redundant now that into_vec is working.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCdZD7sDcJqPAly8r:-OEroQ6n0FiVOpprajw0:b-qy7d44) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L39)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

?
</blockquote></details>

Absolutely. Should I add in the new function documentation that the created vector is with the length of the next multiplicity of N_LANES or is it an implementation detail?
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 94 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoEsBB-c7CgL8I3Y43:-OErprZ-DNpo4Szf8Ksj:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L94)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Does it stands for iterator? can you rename it (it is not an iterator)
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoBuoN4HWOkiqUFXXm:-OErnZxs7AIY4hI4iHUY:b-ef8p2d) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L216)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

to avoid deciding on variable names
</blockquote></details>

I did it because we wanted to delete the len function in MultiplicitiesColumn. I can make this fix with using mults.data.len() for the length, but is it recommended as data is private? 


<!-- Sent from Reviewable.io -->

2024-12-24 09:26 UTC, shaharsamocha7 requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoDahJ2o0GrVMsKiCF:-OEryBnEE81k-zEYb5rD:bg7bfgy) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L74)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Is it a yes or a no? :)
</blockquote></details>

Just do the rename for now
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoFGI78DP__7yFMAvR:-OEryIi1EaHSZpcLJJpK:b-x87ifs) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L93)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Done. Is there a special reason rng should be the first variable to be declared?
</blockquote></details>

Not for functionality.

The first code block is for the test initialization
An internal convention (that I like) is to start by initializing the most "general" things


<!-- Sent from Reviewable.io -->

2024-12-24 09:30 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCdZD7sDcJqPAly8r:-OErzlXaDi5_MuSA8AR8:b-a0q8wm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L39)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Absolutely. Should I add in the new function documentation that the created vector is with the length of the next multiplicity of N_LANES or is it an implementation detail?
</blockquote></details>

i'd say it is not an implementation detail, because you could have chosen to panic if not a multiple of 16, which affects the interface of your sturct.
perhaps the correct place to doc this is above into_simd_vec, because that's where on might ask what happens if I don't initialize with multiple of N_LANES


<!-- Sent from Reviewable.io -->

2024-12-24 09:30 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCdZD7sDcJqPAly8r:-OEs-HcP-RiaQbcJZP9c:b-ke7mdj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L39)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

i'd say it is not an implementation detail, because you could have chosen to panic if not a multiple of 16, which affects the interface of your sturct.
perhaps the correct place to doc this is above into_simd_vec, because that's where on might ask what happens if I don't initialize with multiple of N_LANES
</blockquote></details>

one might ask*


<!-- Sent from Reviewable.io -->

2024-12-24 09:37 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare, @ohad-starkware, and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 74 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoDahJ2o0GrVMsKiCF:-OEs-Ua_31ATwGDk01P2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L74)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Just do the rename for now
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoFGI78DP__7yFMAvR:-OEs0gYvCL6Qq0_q-QYL:btn461w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/mod.rs#L93)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Not for functionality.

The first code block is for the test initialization
An internal convention (that I like) is to start by initializing the most "general" things
</blockquote></details>

Got it
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCdZD7sDcJqPAly8r:-OEs-qQd9Uw2xsH0eKIP:b-syx61x) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L39)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

one might ask*
</blockquote></details>

Yes, but we are also allowing to increase at those extra cells (or maybe it should be enforced?). 
I can add at the into_simd_vec documentation that the last element in the vector is padded with zeros if necessary. so it doesn't depend on the specific implementation.


<!-- Sent from Reviewable.io -->

2024-12-24 09:40 UTC, shaharsamocha7 reviewed
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)



<!-- Sent from Reviewable.io -->

2024-12-24 10:18 UTC, shaharsamocha7 requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 216 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsA2Cn5LInIyU_G2EL:-OEsA2Co1UBdgiCjV7KD:bqae0u0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L216)):*
> ```XML
>         length: mults_vec.len() * N_LANES,
>         data: mults_vec,
>     };
> ```

Consider to implement From for base column



_Code quote:_
```XML
    let multiplicities = BaseColumn {
        length: mults_vec.len() * N_LANES,
        data: mults_vec,
    };
```


<!-- Sent from Reviewable.io -->

2024-12-24 10:19 UTC, shaharsamocha7 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-:-OEsAR5UC025I-wGfEzn:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare and @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 216 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsA2Cn5LInIyU_G2EL:-OEsAMcT9v6lW2C2uLtg:bqhqw8l) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L216)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Consider to implement From for base column
</blockquote></details>

could be done in another pr


<!-- Sent from Reviewable.io -->

2024-12-24 10:27 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: all files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsBxOxEVrEpjSh97S2:-OEsBxOxEVrEpjSh97S3:b-478xz2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
> ```XML
> // TODO(Gali): Move to stwo-air-utils.
> /// An aligned vector of `u32` that is used to store the multiplicities of the columns, for logup
> /// arguments.
> ```

this is both implementation and incorrect
describe only the interface and it's purpose
also lookup instead of logup



_Code quote:_
```XML
/// An aligned vector of `u32` that is used to store the multiplicities of the columns, for logup
/// arguments.
```


<!-- Sent from Reviewable.io -->

2024-12-24 10:30 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 69 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsChdb85JjHuqVetUl:-OEsChdb85JjHuqVetUm:big54rl) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L69)):*
> ```XML
>     }
> 
>     pub fn increase_at(&mut self, address: usize) {
> ```

I think that more often than not, the address will be u32, so maybe take u32 instead and do the cast in here?


<!-- Sent from Reviewable.io -->

2024-12-24 10:31 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 216 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoBuoN4HWOkiqUFXXm:-OEsCzjfCW-EiRGZ5cA_:bgfop5w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L216)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

I did it because we wanted to delete the len function in MultiplicitiesColumn. I can make this fix with using mults.data.len() for the length, but is it recommended as data is private?
</blockquote></details>

oh right right nevermind me


<!-- Sent from Reviewable.io -->

2024-12-24 10:33 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: all files reviewed, 4 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCdZD7sDcJqPAly8r:-OEsCGV33GqOgQH2mA9U:b-23z7zn) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L39)):*
<details><summary><i>Previously, Gali-StarkWare wrote…</i></summary><blockquote>

Yes, but we are also allowing to increase at those extra cells (or maybe it should be enforced?). 
I can add at the into_simd_vec documentation that the last element in the vector is padded with zeros if necessary. so it doesn't depend on the specific implementation.
</blockquote></details>

alrighty
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 216 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsA2Cn5LInIyU_G2EL:-OEsD9oY4x2V1suHjwiM:bi63cfx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L216)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

could be done in another pr
</blockquote></details>

not directly on the struct, because we really do want Vec<PackedM31> (it's a lookup data)
but From<Vec<PackedM31>> for BaseColumn would be a positive change


<!-- Sent from Reviewable.io -->

2024-12-24 12:02 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 56 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsBxOxEVrEpjSh97S2:-OEsX8hQC0kRhFDzWKF3:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L56)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

this is both implementation and incorrect
describe only the interface and it's purpose
also lookup instead of logup
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 69 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsChdb85JjHuqVetUl:-OEsWNrr6r0v0bDYJ73m:bk20rzo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/mod.rs#L69)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I think that more often than not, the address will be u32, so maybe take u32 instead and do the cast in here?
</blockquote></details>

Smart, done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 39 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEoCdZD7sDcJqPAly8r:-OEsVw4ZATXMF-I4Mt7P:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1b2cfe5772e4d163e673358452c47cb07a4134f6/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L39)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

alrighty
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs` line 216 at r5](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsA2Cn5LInIyU_G2EL:-OEsXArh1MnNq004MueM:b9tajqv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/1c049c5af6ad33d134c906101c18bf9676fe9c9e/stwo_cairo_prover/crates/prover/src/components/memory/memory_id_to_big/prover.rs#L216)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

not directly on the struct, because we really do want Vec<PackedM31> (it's a lookup data)
but From<Vec<PackedM31>> for BaseColumn would be a positive change
</blockquote></details>

I'll open another PR for that then


<!-- Sent from Reviewable.io -->

2024-12-24 12:10 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsYtiI5zG1THRKfMTk:-OEsYtiI5zG1THRKfMTl:bhz5otx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aee8d0139a250f97f0571b98bfff1f47f840e7e2/stwo_cairo_prover/crates/prover/src/components/mod.rs#L57)):*
> ```XML
> /// A column of multiplicities for lookup arguments.
> /// Allows increasing the multiplicity of an element at a given address and converting the data to a
> /// vector of PackedM31.
> ```

imo this is too many words, also address is in-accurate



_Suggestion:_
```XML
/// Allows increasing the multiplicity at a given index.
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 92 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsZ_gX5K7H0koK0e6C:-OEsZZ3A7BYt3k_BAuBu:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aee8d0139a250f97f0571b98bfff1f47f840e7e2/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L92)):*
> ```XML
>             .array_chunks::<N_LANES>()
>             .map(|&chunk| unsafe { PackedM31::from_simd_unchecked(Simd::from_array(chunk)) });
>         let multiplicities_vec = self.multiplicities.into_simd_vec();
> ```





_Suggestion:_
```XML
multiplicities
```


<!-- Sent from Reviewable.io -->

2024-12-24 13:52 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 57 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsYtiI5zG1THRKfMTk:-OEsvxX-C6DpkfjZAyKT:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aee8d0139a250f97f0571b98bfff1f47f840e7e2/stwo_cairo_prover/crates/prover/src/components/mod.rs#L57)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

imo this is too many words, also address is in-accurate
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 92 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEsZ_gX5K7H0koK0e6C:-OEsw4ZM7g86_VAKtXnp:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/aee8d0139a250f97f0571b98bfff1f47f840e7e2/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L92)):*
> ```XML
>             .array_chunks::<N_LANES>()
>             .map(|&chunk| unsafe { PackedM31::from_simd_unchecked(Simd::from_array(chunk)) });
>         let multiplicities_vec = self.multiplicities.into_simd_vec();
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 14:08 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Gali-StarkWare and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEszc3b3J5k9u7oeRSi:-OEszc3c9lXWdZGdHvUW:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877c2ea75884ebf8b137c67865e68fb75ec5e848/stwo_cairo_prover/crates/prover/src/components/mod.rs#L55)):*
> ```XML
> 
> // TODO(Gali): Move to stwo-air-utils.
> /// A column of multiplicities for lookup arguments. Allows increasing the multiplicity  at a given
> ```




<!-- Sent from Reviewable.io -->

2024-12-24 14:08 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEszozl0qzeEuj4Ti7Y:-OEszozl0qzeEuj4Ti7Z:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877c2ea75884ebf8b137c67865e68fb75ec5e848/stwo_cairo_prover/crates/prover/src/components/mod.rs#L55)):*
> ```XML
> 
> // TODO(Gali): Move to stwo-air-utils.
> /// A column of multiplicities for lookup arguments. Allows increasing the multiplicity  at a given
> ```





_Suggestion:_
```XML
/// A column of multiplicities for lookup arguments. Allows increasing the multiplicity at a given
```


<!-- Sent from Reviewable.io -->

2024-12-24 14:51 UTC, Gali-StarkWare reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware and @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/mod.rs` line 55 at r7](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-OEszozl0qzeEuj4Ti7Y:-OEt8hymAqDfgdNHzXS6:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/877c2ea75884ebf8b137c67865e68fb75ec5e848/stwo_cairo_prover/crates/prover/src/components/mod.rs#L55)):*
> ```XML
> 
> // TODO(Gali): Move to stwo-air-utils.
> /// A column of multiplicities for lookup arguments. Allows increasing the multiplicity  at a given
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 15:07 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/271#-:-OEtCQpL8rcXHJkNCMXL:bnfp4nl)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2024-12-24 15:16 UTC, Gali-StarkWare commented
### Merge activity

* **Dec 24, 10:16 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/271).

2024-12-24 15:17 UTC, merged