Add seq preprocessed columns to cairo air
starkware-libs/stwo-cairo pull request #292
Opened 2024-12-31 11:29 UTC by shaharsamocha7

2024-12-31 11:30 UTC, shaharsamocha7 commented
* **#292** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/292?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/292?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-31 11:44 UTC, ohad-starkware requested changes
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292#-OFRViRn3QwYDXG4lFmr:-OFRViRn3QwYDXG4lFms:b3bcf7e) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e5f285bcaf57a0538ef99a35ddb2f03b5141fc62/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
> ```XML
> const SEQ_LOG_SIZES: [u32; 19] = [
>     22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4,
> ];
> ```

it is possible to couple those?
you would want to increase is first together with seq (otherway around not but still sucks and performance is the same)



_Code quote:_
```XML
const IS_FIRST_LOG_SIZES: [u32; 19] = [
    22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4,
];
const SEQ_LOG_SIZES: [u32; 19] = [
    22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4,
];
```
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292#-OFRX1Ir5ZNEtddTsW-Q:-OFRX1Ir5ZNEtddTsW-R:b2sw78c) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e5f285bcaf57a0538ef99a35ddb2f03b5141fc62/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L105)):*
> ```XML
>         // Lookup data.
>         let log_size = size.checked_ilog2().unwrap();
>         let addresses = PreprocessedColumn::gen_preprocessed_column::<SimdBackend>(
> ```

do you have to generate the values?
you can call packed_at during trace gen (and interaction gen)


<!-- Sent from Reviewable.io -->

2024-12-31 13:54 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292#-OFRViRn3QwYDXG4lFmr:-OFRzYqF6rS-qiL9-VQ8:b-d21yvp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e5f285bcaf57a0538ef99a35ddb2f03b5141fc62/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L30)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

it is possible to couple those?
you would want to increase is first together with seq (otherway around not but still sucks and performance is the same)
</blockquote></details>

I'm not sure they should be coupled.
I imagine that we have less Seq columns, and maybe we will remove IsFirst soon enough.
___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292#-OFRX1Ir5ZNEtddTsW-Q:-OFRzKau-F9AsNC_a0z0:bc0bavk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e5f285bcaf57a0538ef99a35ddb2f03b5141fc62/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L105)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

do you have to generate the values?
you can call packed_at during trace gen (and interaction gen)
</blockquote></details>

I only need it for interaction trace gen and currently LookupData gets the vector of addresses.
Don't see a reason to change it


<!-- Sent from Reviewable.io -->

2024-12-31 14:02 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292#-OFRX1Ir5ZNEtddTsW-Q:-OFS0CkF3IScG9O_XfVa:bqrc1zp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e5f285bcaf57a0538ef99a35ddb2f03b5141fc62/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L105)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

I only need it for interaction trace gen and currently LookupData gets the vector of addresses.
Don't see a reason to change it
</blockquote></details>

you can use packed at there also no?


<!-- Sent from Reviewable.io -->

2025-01-01 06:25 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs` line 105 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292#-OFRX1Ir5ZNEtddTsW-Q:-OFVXfTVAQfG2rcUPQX2:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e5f285bcaf57a0538ef99a35ddb2f03b5141fc62/stwo_cairo_prover/crates/prover/src/components/memory/memory_address_to_id/prover.rs#L105)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

you can use packed at there also no?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 06:52 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/292#-:-OFVcnFw0u4B0lx3h0nZ:bnfp4nl)* status: 1 of 7 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-01 13:47 UTC, shaharsamocha7 commented
### Merge activity

* **Jan 1, 8:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/292).

2025-01-01 13:47 UTC, merged