DO NOT MERGE: Git experiment
starkware-libs/stwo-cairo pull request #294
Opened 2024-12-31 13:32 UTC by yuvalsw

2024-12-31 13:52 UTC, Stavbe requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294#-OFRvQ5d3aKCQklPcFYb:-OFRvQ5d3aKCQklPcFYc:b3f3leo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bc0cc64b83f234e0fa7e1edc4e0f2f8f5cd9cd0c/stwo_cairo_prover/crates/prover/src/input/plain.rs#L28)):*
> ```XML
>         .collect_vec();
> 
>     // TODO(yg): revert
> ```

very bad


<!-- Sent from Reviewable.io -->

2024-12-31 13:53 UTC, Stavbe approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294#-OFRzSlxAWdMJhb6NBhH:-OFRzSlxAWdMJhb6NBhI:b-3my0w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/bc0cc64b83f234e0fa7e1edc4e0f2f8f5cd9cd0c/stwo_cairo_prover/crates/prover/src/input/plain.rs#L29)):*
> ```XML
> 
>     // TODO(yg): revert
>     let program_len = felt_code.len();
> ```

very very bad 


<!-- Sent from Reviewable.io -->

2025-01-02 12:22 UTC, Stavbe approved these changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @yuvalsw)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294#-OFaxblq7fkEmOh8ry5A:-OFaxblr7cXrwwKPaDsA:b-yzixad) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17a6246979772ff92317922c896be9296959fb8e/stwo_cairo_prover/crates/prover/src/input/plain.rs#L29)):*
> ```XML
> 
>     // TODO(yg): revertttt
>     let program_len = felt_code.len();
> ```

test test


<!-- Sent from Reviewable.io -->

2025-01-02 12:35 UTC, yuvalsw reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yuvalsw)



<!-- Sent from Reviewable.io -->

2025-01-02 12:37 UTC, yuvalsw reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294)* status: all files reviewed, 1 unresolved discussion (waiting on @Stavbe)

___
*[`stwo_cairo_prover/crates/prover/src/input/plain.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/294#-OFb0OKn6QkeY_rqzD3T:-OFb0OKo8uvzfGaHqIY-:b-rstwbf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/17a6246979772ff92317922c896be9296959fb8e/stwo_cairo_prover/crates/prover/src/input/plain.rs#L31)):*
> ```XML
>     let program_len = felt_code.len();
>     let program = cairo_vm::types::program::Program::new_for_proof(
>         vec![],
> ```

dfgdfg


<!-- Sent from Reviewable.io -->

2025-01-20 15:14 UTC, closed without merging