Preprocessed trace gen
starkware-libs/stwo-cairo pull request #295
Opened 2024-12-31 13:55 UTC by shaharsamocha7

2024-12-31 13:55 UTC, shaharsamocha7 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/295?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#295** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/295?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/295?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#292** <a href="https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/292?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-31 14:10 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFS2Sza-eA6NFUbIZ3J:-OFS2Sza-eA6NFUbIZ3K:b-5fbb08) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/36fd55f2f1e2a02e11aa67ee015e8da95b8f1299/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L15)):*
> ```XML
> 
> // Returns the preprocessed columns info for the preprocessed trace.
> pub fn preprocessed_trace_columns() -> Vec<PreprocessedColumn> {
> ```

non blocking,
for const concat you can use this https://www.reddit.com/r/rust/comments/zqwggh/how_to_concat_two_const_slices_in_a_const_way/


<!-- Sent from Reviewable.io -->

2024-12-31 14:22 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295)* status: 0 of 5 files reviewed, all discussions resolved

___
*[`stwo_cairo_prover/Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFS1gvV5SpBlYaTptaC:-OFS1gvV5SpBlYaTptaD:bq2cxrv) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/36fd55f2f1e2a02e11aa67ee015e8da95b8f1299/stwo_cairo_prover/Cargo.toml#L39)):*
> ```TOML
> stwo_cairo_utils = { path = "crates/utils", version = "~0.1.0" }
> # TODO(ShaharS): take stwo version from the source repository.
> stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "f9f5b09", features = [
> ```

be careful when merging
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFS4dCF28zjQrmYw9xv:-OFS4dCF28zjQrmYw9xw:b-w8qyd7) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c0fb88f895d5bf8c651e47968f4ad60ce3f806f1/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L42)):*
> ```XML
> 
>     #[test]
>     fn test_preprocessed_trace_columns() {
> ```

?
the test is already in a preprocessed context



_Suggestion:_
```XML
 fn test_columns_are_in_decending_order() 
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFS4nYA7d5CVEklGVZz:-OFS4nYA7d5CVEklGV_-:b2ni8l0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/c0fb88f895d5bf8c651e47968f4ad60ce3f806f1/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L50)):*
> ```XML
>             assert!(column.log_size() <= size);
>             size = column.log_size();
>         }
> ```

nit



_Suggestion:_
```XML

        assert!(
            columns
                .windows(2)
                .all(|w| w[0].log_size() >= w[1].log_size())
        );
```


<!-- Sent from Reviewable.io -->

2025-01-01 07:06 UTC, ohad-starkware requested changes
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @shaharsamocha7)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFVd6D53yASUFThDXP0:-OFVd6D53yASUFThDXP1:b-amov49) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/edd7716d575d09b865fcdfec1f9324495dd0b361/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L14)):*
> ```XML
> ];
> 
> // Returns the preprocessed columns info for the preprocessed trace.
> ```

also you have the word 'preprocessed' twice in the doc, and twice more in the signature



_Suggestion:_
```XML
/// Returns the preprocessed columns info for the preprocessed trace.
```
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFVfSu45LNQaZudSjPP:-OFVfSu45LNQaZudSjPQ:b45h) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/edd7716d575d09b865fcdfec1f9324495dd0b361/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L34)):*
> ```XML
>     // Columns should be in descending order of log size.
>     res.sort_by_key(|b| std::cmp::Reverse(b.log_size()));
>     res
> ```





_Suggestion:_
```XML
    // Columns should be in descending order of log size.
    let is_first_columns = IS_FIRST_LOG_SIZES.map(PreprocessedColumn::IsFirst);
    let seq_columns = SEQ_LOG_SIZES.map(PreprocessedColumn::Seq);
    [is_first_columns, seq_columns]
        .into_iter()
        .flat_map(|columns| columns.into_iter())
        .sorted_by_key(|column| std::cmp::Reverse(column.log_size()))
        .collect()
```


<!-- Sent from Reviewable.io -->

2025-01-01 08:56 UTC, shaharsamocha7 reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFS2Sza-eA6NFUbIZ3J:-OFVoCVUAP8Z7liQARcS:bl7nfve) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/36fd55f2f1e2a02e11aa67ee015e8da95b8f1299/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L15)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

non blocking,
for const concat you can use this https://www.reddit.com/r/rust/comments/zqwggh/how_to_concat_two_const_slices_in_a_const_way/
</blockquote></details>

I also need the sorting thing, will leave it non-const for now
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFVd6D53yASUFThDXP0:-OFVo1Zk8T-TWdCUEPdi:b-ixgjhx) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/edd7716d575d09b865fcdfec1f9324495dd0b361/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L14)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

also you have the word 'preprocessed' twice in the doc, and twice more in the signature
</blockquote></details>

Done.
What's wrong with preprocessed written here?
___
*[`stwo_cairo_prover/Cargo.toml` line 39 at r1](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFS1gvV5SpBlYaTptaC:-OFW4DLQ4nOuMApOE8bB:bvth56w) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/36fd55f2f1e2a02e11aa67ee015e8da95b8f1299/stwo_cairo_prover/Cargo.toml#L39)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

be careful when merging
</blockquote></details>

reverted
___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 34 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFVfSu45LNQaZudSjPP:-OFW4BNvAkvCR-VD3rZS:b-el3i9k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/edd7716d575d09b865fcdfec1f9324495dd0b361/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L34)):*
> ```XML
>     // Columns should be in descending order of log size.
>     res.sort_by_key(|b| std::cmp::Reverse(b.log_size()));
>     res
> ```

Done.
ty


<!-- Sent from Reviewable.io -->

2025-01-01 09:05 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs` line 14 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFVd6D53yASUFThDXP0:-OFW5ehj3Ot5z_yYn_rb:bf8w94j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/edd7716d575d09b865fcdfec1f9324495dd0b361/stwo_cairo_prover/crates/prover/src/cairo_air/preprocessed.rs#L14)):*
<details><summary><i>Previously, shaharsamocha7 wrote…</i></summary><blockquote>

Done.
What's wrong with preprocessed written here?
</blockquote></details>

it should be written, but is it not trivial that the preprocessed trace consists of preprocessed columns?
/// Returns column info for the preprocessed trace.


<!-- Sent from Reviewable.io -->

2025-01-01 09:06 UTC, ohad-starkware commented
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFW6WhUDgCEVMLOE6zG:-OFW6WhUDgCEVMLOE6zH:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9593e129706b6af3a75fdae0785e399e1f3d900b/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L63)):*
> ```XML
>             .iter()
>             .map(PreprocessedColumn::gen_preprocessed_column::<SimdBackend>)
>             .collect_vec(),
> ```




<!-- Sent from Reviewable.io -->

2025-01-01 09:07 UTC, ohad-starkware reviewed
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @shaharsamocha7)



<!-- Sent from Reviewable.io -->

2025-01-01 11:27 UTC, shaharsamocha7 reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs` line 63 at r4](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-OFW6WhUDgCEVMLOE6zG:-OFWbddk669SsWMUKjpW:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/9593e129706b6af3a75fdae0785e399e1f3d900b/stwo_cairo_prover/crates/prover/src/cairo_air/mod.rs#L63)):*
> ```XML
>             .iter()
>             .map(PreprocessedColumn::gen_preprocessed_column::<SimdBackend>)
>             .collect_vec(),
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-01 13:08 UTC, ohad-starkware approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/295#-:-OFWyo_hAL704WlFKswt:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-01 13:47 UTC, shaharsamocha7 commented
### Merge activity

* **Jan 1, 8:47 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/stwo-cairo/295).

2025-01-01 13:57 UTC, merged