pc column interaction trace
starkware-libs/stwo-cairo pull request #31
Opened 2024-07-24 08:43 UTC by ohad-starkware

2024-07-24 11:58 UTC, alonh5 requested changes
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31)* status: 6 of 7 files reviewed, 15 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZFq_35bxcAprsggx0:-O2ZFq_35bxcAprsggx1:bz6axst) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L1)):*
> ```XML
> #![allow(unused_imports)]
> ```

Why do we need this? Can you just remove the unused ones?
The `allow` macro should only be used meticulously.



_Code quote:_
```XML
#![allow(unused_imports)]
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZEleABeZVMNecSEbN:-O2ZEleABeZVMNecSEbO:bo5kjh8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L44)):*
> ```XML
>     fn trace_log_degree_bounds(&self) -> TreeVec<Vec<u32>> {
>         TreeVec(vec![
>             vec![self.log_n_instances; 7],
> ```

Create a constant for this and use it everywhere.



_Code quote:_
```XML
7
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 45 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZEt6471KODvCOZE1M:-O2ZEt6471KODvCOZE1N:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L45)):*
> ```XML
>         TreeVec(vec![
>             vec![self.log_n_instances; 7],
>             vec![self.log_n_instances; 4],
> ```





_Suggestion:_
```XML
SECURE_EXTENSION_DEGREE
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZGsgnDB5_rLaA-kjJ:-O2ZGsgnDB5_rLaA-kjK:b7izx1q) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L1)):*
> ```XML
> #![cfg(test)]
> ```

Move this to the mod declaration in `ret/mod.rs`.



_Code quote:_
```XML
#![cfg(test)]
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZNeAqDncRXflf3xq6:-O2ZNeAqDncRXflf3xq7:b-8ou7qj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L24)):*
> ```XML
> };
> 
> pub fn register_test_ret_memory(registry: &mut ComponentGenerationRegistry) {
> ```

Can you use the `register_test_memory`? TAL at my branch I put it in a common test_utils file.
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZP0MA6HhtrT_rAa-e:-O2ZP0MA6HhtrT_rAa-f:bgkwcxk) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L56)):*
> ```XML
> }
> 
> pub(crate) struct TestRetAirGenerator {
> ```

Code in test modules can't be used outside the crate.



_Suggestion:_
```XML
pub
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZQbZb74lGHOEEpINO:-O2ZQbZb74lGHOEEpINP:bl84e85) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L81)):*
> ```XML
> impl AirTraceGenerator<CpuBackend> for TestRetAirGenerator {
>     fn write_trace(&mut self) -> Vec<CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>> {
>         // TODO(Ohad): add memory trace.
> ```

Still relevant?



_Code quote:_
```XML
// TODO(Ohad): add memory trace.
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZSj9LBJdB-hxNEVAg:-O2ZSj9LBJdB-hxNEVAh:b-xx1c2j) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L95)):*
> ```XML
>     ) -> Vec<CircleEvaluation<CpuBackend, BaseField, BitReversedOrder>> {
>         let ret_trace = trace.iter().take(7).collect_vec();
>         let memory_trace = trace.iter().skip(7).collect_vec();
> ```

Why 7?



_Code quote:_
```XML
let memory_trace = trace.iter().skip(7).collect_vec();
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUK_e5br3e3KU3awJ:-O2ZUK_e5br3e3KU3awK:b-kcxc5a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L26)):*
> ```XML
> };
> 
> #[allow(non_camel_case_types)]
> ```

Why is this needed?
Also about all the `allow` macros in this file



_Code quote:_
```XML
#[allow(non_camel_case_types)]
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUoST-P793FhGgUX-:-O2ZUoST-P793FhGgUX0:b-ar1gyj) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L34)):*
> ```XML
> impl ComponentTraceGenerator<CpuBackend> for RetOpcodeCpuTraceGenerator {
>     type Component = RetOpcode;
>     type Inputs = Vec<[M31; 3]>;
> ```

What are the inputs to ret? Why is it 3?



_Code quote:_
```XML
type Inputs = Vec<[M31; 3]>;
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUtl24KuKjLsSQu8u:-O2ZUtl24KuKjLsSQu8v:undefined) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L66)):*
> ```XML
>                 .len()
>                 .checked_ilog2()
>                 .expect("Input not a power of 2!"),
> ```





_Suggestion:_
```XML
Input is not a power of 2!
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 102 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZVX184VnFAiffiA_M:-O2ZVX184VnFAiffiA_N:b-rztz8) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L102)):*
> ```XML
>                 log_domain_size,
>             );
>             prefix_sum += denom_inverses[index];
> ```

Nice, that's better than what I did.



_Code quote:_
```XML
prefix_sum += denom_inverses[index];
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZZbeP7Jv2iRFFFvDK:-O2ZZbeP7Jv2iRFFFvDL:btjgdbz) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L134)):*
> ```XML
> pub fn write_trace_cpu(
>     component: &RetOpcode,
>     secrets: &Vec<[M31; 3]>,
> ```

What are secrets?



_Code quote:_
```XML
secrets
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZWnym1EgKOmZuceyr:-O2ZWnym1EgKOmZuceys:b-ier5c5) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L142)):*
> ```XML
>     let n_trace_columns = component.trace_log_degree_bounds()[ [...]

2024-07-24 14:18 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31)* status: 6 of 7 files reviewed, 14 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZFq_35bxcAprsggx0:-O2_15Ox8gSNVob4V1-W:b1778bc) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why do we need this? Can you just remove the unused ones?
The `allow` macro should only be used meticulously.
</blockquote></details>

codegen artifact, removed
___
*[`stwo_cairo_prover/src/components/ret_opcode/component.rs` line 44 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZEleABeZVMNecSEbN:-O2_1oz33ZDy7_Siuanl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/component.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Create a constant for this and use it everywhere.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZGsgnDB5_rLaA-kjJ:-O2_2-BW8GixD-o1i3Hn:b-sfc3lb) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Move this to the mod declaration in `ret/mod.rs`.
</blockquote></details>

I put all the stuff inside the tests mod instead
  
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZNeAqDncRXflf3xq6:-O2_2DZW9zRxFIO2tdwf:b-ilufo) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L24)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you use the `register_test_memory`? TAL at my branch I put it in a common test_utils file.
</blockquote></details>

I needed specific values in the memory
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZP0MA6HhtrT_rAa-e:-O2_2K3yDo_Vw43-_3GJ:bdv6zfr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L56)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Code in test modules can't be used outside the crate.
</blockquote></details>

for some reason it doesnt scream about the "new" instead of default when I add this
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZQbZb74lGHOEEpINO:-O2_3YU-7-l6cKMlxjfx:b32wsm) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L81)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Still relevant?
</blockquote></details>

no
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZSj9LBJdB-hxNEVAg:-O2_3ZaoAwmQvBhtiKfT:b-s185pr) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L95)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why 7?
</blockquote></details>

7 first columns are ret columns
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUK_e5br3e3KU3awJ:-O2_40PR6BYSerYaO8rE:b-ovf430) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L26)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why is this needed?
Also about all the `allow` macros in this file
</blockquote></details>

they are not
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUoST-P793FhGgUX-:-O2ZggZA0hbgTsMx-K_E:b-oxlzwt) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L34)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What are the inputs to ret? Why is it 3?
</blockquote></details>

pc ap fp
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 134 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZZbeP7Jv2iRFFFvDK:-O2_4Gju1PoYpfyIJpLy:bajm68u) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L134)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

What are secrets?
</blockquote></details>

inputs,
I need to change this in the codegen also
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZWnym1EgKOmZuceyr:-O2_5Vwn9HJBsApEKRCy:b-gf6jfq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L142)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Add a TODO to consider adding the inputs one by one and not storing them first and then dumping them.
</blockquote></details>

discussed
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2Z_KSOAv5rUEay6qc1:-O2_5ZTaE7_HeDdrZj44:b-74c12f) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L184)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

why are there jumps in the numbering?
</blockquote></details>

autogen artifact, gave meaningful names.
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2Za0zMA6jQBD0AvSyi:-O2_5f_b3Jt4bkHV1o6n:b-p78cep) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L187)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you explain the minus 1 (and minus 2 in the next one)?
</blockquote></details>

ret trace row:
pc | ap | fp | [fp-1].0 | [fp-1].1 | [fp-2].0 | [fp-2].1


<!-- Sent from Reviewable.io -->

2024-07-25 07:27 UTC, alonh5 requested changes
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31)* status: 6 of 7 files reviewed, 8 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZGsgnDB5_rLaA-kjJ:-O2chLIN8LVMJuX_iOZJ:b-m4uevu) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L1)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

I put all the stuff inside the tests mod instead
</blockquote></details>

Now it's a test module inside `test_utils.rs`. Is that what you meant? is it testing the test utils?
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZSj9LBJdB-hxNEVAg:-O2chnbLEaprFHQLT4W9:b-m8nsb0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L95)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

7 first columns are ret columns
</blockquote></details>

Still the interaction trace generator should get all of the column, even if some aren't used for ret. Use `N_MEMORY_COLUMNS`.
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUoST-P793FhGgUX-:-O2cmPGpDoEPeaUKCuA8:b-nvtpur) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L34)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

pc ap fp
</blockquote></details>

Create a constant?
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2Z_KSOAv5rUEay6qc1:-O2ckTdP5S8H3lDD9HUQ:brc7rp2) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L184)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

autogen artifact, gave meaningful names.
</blockquote></details>

I think it's okay  it will match the autogen, I was just wondering why there was a jump.
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2Za0zMA6jQBD0AvSyi:-O2clEJm1v0KhBBDqO04:b-jq3n9a) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L187)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

ret trace row:
pc | ap | fp | [fp-1].0 | [fp-1].1 | [fp-2].0 | [fp-2].1
</blockquote></details>

should be 3 m31's for each of the memory values (Can be done in a new PR).
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 153 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2clpUU3Zpo34comQMy:-O2clpUU3Zpo34comQMz:b2ctyu4) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fa40168ad0e901484d6347f381c83b87148a59f2/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L153)):*
> ```XML
>                 eval.len()
>                     .checked_ilog2()
>                     .expect("Input is not a power of 2!"),
> ```

Why must the number of inputs be a power of 2? Couldn't there be any number of ret's in a program?
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 171 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2cl4NKC-RMwQT0gYnG:-O2cl4NKC-RMwQT0gYnH:b-v1f2v0) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fa40168ad0e901484d6347f381c83b87148a59f2/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L171)):*
> ```XML
> ) {
>     let deduction_tmp_0 = [
>         ret_opcode_input[0],
> ```

Can you make the autogen convert from CamelCase to snake_case?


<!-- Sent from Reviewable.io -->

2024-07-25 08:16 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @alonh5 and @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 1 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZGsgnDB5_rLaA-kjJ:-O2cnhCOCgUMc50OAuSR:b9l8n7n) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L1)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Now it's a test module inside `test_utils.rs`. Is that what you meant? is it testing the test utils?
</blockquote></details>

ahhh I understand
reverted that
___
*[`stwo_cairo_prover/src/components/ret_opcode/test_utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZSj9LBJdB-hxNEVAg:-O2cpaDrCscmhcVQrRHh:bv9gzfh) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/test_utils.rs#L95)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Still the interaction trace generator should get all of the column, even if some aren't used for ret. Use `N_MEMORY_COLUMNS`.
</blockquote></details>

I think it's the same way in your code #30 
only you used the same iterator and avoided the skip
changed to do the same
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUoST-P793FhGgUX-:-O2co-sM2wDgHoLgmgoP:brujr21) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L34)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Create a constant?
</blockquote></details>

don't think it shows up again
I tried to do it in the autogen, but inputs can potentially be tuples of different types, say a pair of different sized arrays.
What would be a good name for these? I couldn't find.
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 66 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUtl24KuKjLsSQu8u:-O2crAqUA_C8Xq6GWuls:bb7f2mf) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L66)):*
> ```XML
>                 .len()
>                 .checked_ilog2()
>                 .expect("Input not a power of 2!"),
> ```

done
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 184 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2Z_KSOAv5rUEay6qc1:-O2crTXA02XQIaGA2EYA:b-xoyf6s) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L184)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

I think it's okay  it will match the autogen, I was just wondering why there was a jump.
</blockquote></details>

here it's because 'let col_i = something' is also a deduction, 
but It stays as an r_value so the name is skipped.
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 187 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2Za0zMA6jQBD0AvSyi:-O2codfA9337Z1g8NvxR:bgvs52k) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L187)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

should be 3 m31's for each of the memory values (Can be done in a new PR).
</blockquote></details>

will do 
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 153 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2clpUU3Zpo34comQMy:-O2crCnt5lGgScgIKMCi:b-grq9zq) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fa40168ad0e901484d6347f381c83b87148a59f2/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L153)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Why must the number of inputs be a power of 2? Couldn't there be any number of ret's in a program?
</blockquote></details>


added a todo
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 171 at r3](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2cl4NKC-RMwQT0gYnG:-O2crOXnCzmLR_BXjt0n:b-q15tro) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/fa40168ad0e901484d6347f381c83b87148a59f2/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L171)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Can you make the autogen convert from CamelCase to snake_case?
</blockquote></details>

yes that's a good idea


<!-- Sent from Reviewable.io -->

2024-07-25 13:46 UTC, alonh5 requested changes
> Reviewed 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31)* status: all files reviewed, 4 unresolved discussions (waiting on @ohad-starkware)

___
*[`stwo_cairo_prover/src/components/ret_opcode/mod.rs` line 3 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2e45ct8X2_h9CGk2JG:-O2e45ct8X2_h9CGk2JH:bm68xsp) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e38c5d9d01995eaeb82e8d0268abcfc399ede95b/stwo_cairo_prover/src/components/ret_opcode/mod.rs#L3)):*
> ```XML
> pub mod component;
> pub mod cpu_prover;
> pub mod test_utils;
> ```

This is what I meant.



_Suggestion:_
```XML
#[cfg(test)]
pub mod test_utils;
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/mod.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2e4uC07fzlEwoVuEbE:-O2e4uC07fzlEwoVuEbF:buwwqzw) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e38c5d9d01995eaeb82e8d0268abcfc399ede95b/stwo_cairo_prover/src/components/ret_opcode/mod.rs#L44)):*
> ```XML
>             .interact(&trace, &interaction_elements)
>             .into_iter()
>             .take(4)
> ```

Use constant.



_Code quote:_
```XML
4
```
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUoST-P793FhGgUX-:-O2e6uAs9bE9EQYJyXaQ:b-wywaic) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L34)):*
<details><summary><i>Previously, ohad-starkware (Ohad) wrote…</i></summary><blockquote>

don't think it shows up again
I tried to do it in the autogen, but inputs can potentially be tuples of different types, say a pair of different sized arrays.
What would be a good name for these? I couldn't find.
</blockquote></details>

Maybe N_POINTERS? It appears a few times here, but won't it also appear in other opcodes, like call for example? You can add to it if  there are more felt in the input


<!-- Sent from Reviewable.io -->

2024-07-29 06:35 UTC, ohad-starkware reviewed
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @alonh5)

___
*[`stwo_cairo_prover/src/components/ret_opcode/mod.rs` line 3 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2e45ct8X2_h9CGk2JG:-O2eAfc2Dq_RgT3f5pVl:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e38c5d9d01995eaeb82e8d0268abcfc399ede95b/stwo_cairo_prover/src/components/ret_opcode/mod.rs#L3)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

This is what I meant.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/ret_opcode/mod.rs` line 44 at r6](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2e4uC07fzlEwoVuEbE:-O2eGGtjEPXnigZ3NMEy:b-896fix) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/e38c5d9d01995eaeb82e8d0268abcfc399ede95b/stwo_cairo_prover/src/components/ret_opcode/mod.rs#L44)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Use constant.
</blockquote></details>

Done.
___
*[`stwo_cairo_prover/src/components/ret_opcode/trace.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31#-O2ZUoST-P793FhGgUX-:-O2e8liW-bLsOevBmnNX:bbzjx0z) ([raw file](https://github.com/starkware-libs/stwo-cairo/blob/858cc77ff30b0d4c2853e7627d0f5461a93b36ae/stwo_cairo_prover/src/components/ret_opcode/trace.rs#L34)):*
<details><summary><i>Previously, alonh5 (Alon Haramati) wrote…</i></summary><blockquote>

Maybe N_POINTERS? It appears a few times here, but won't it also appear in other opcodes, like call for example? You can add to it if  there are more felt in the input
</blockquote></details>

so specifcally for opcodes? 
I think that will work. N_REGISTERS.
won't autogen this but its a good cosmetic change


<!-- Sent from Reviewable.io -->

2024-07-29 07:24 UTC, alonh5 approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/stwo-cairo/31)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ohad-starkware)



<!-- Sent from Reviewable.io -->

2024-07-29 14:30 UTC, merged